
import {UiText,UiField,UiOption} from '../../ui-language';
import {restaurantOnly} from '../../../lib/pos-access';
import {currentUser} from '../../../lib/auth';
import {stayView,money} from '../../../lib/stays';
import PrintBill from './print';
import './print.css';
export const dynamic='force-dynamic';
export default async function BillPage({params}:{params:Promise<{id:string}>}){const u=await currentUser();if(!u||restaurantOnly(u)||u.role==='guest')return <main><UiText>Staff login is required to view this bill. </UiText><a href="/"><UiText>Return to login</UiText></a></main>;const {id}=await params;try{const d=await stayView(),s=d.stays.find((s:any)=>s.id===id);if(!s)return <main><UiText>Bill not found.</UiText></main>;return <main className="print-bill"><nav className="print-control"><a href={'/?portal='+u.role+'&room='+s.room}><UiText>← Back to room</UiText></a><PrintBill/></nav><header><h1><UiText>NIRILI VILLA</UiText></h1><p><UiText>Dhiffushi Island, Kaafu Atoll, Maldives</UiText></p><h2><UiText>Guest Bill · </UiText><UiText>{s.id}</UiText></h2></header><section className="bill-meta"><p><b><UiText>Guest:</UiText></b> {s.guest}</p><p><b><UiText>Room:</UiText></b> <UiText>{s.room}</UiText> · <UiText>{s.pax}</UiText> <UiText>adults</UiText></p><p><b><UiText>Stay:</UiText></b> <UiText>{s.checkIn}</UiText> <UiText>to </UiText><UiText>{s.checkOut}</UiText></p><p><b><UiText>Meal plan:</UiText></b> <UiText>{s.meal}</UiText></p><p><b><UiText>Status:</UiText></b> <UiText>{s.status}</UiText></p></section><table><thead><tr><th><UiText>Bill / Item</UiText></th><th><UiText>Qty</UiText></th><th><UiText>Amount</UiText></th><th><UiText>Discount</UiText></th><th><UiText>Total</UiText></th></tr></thead><tbody><UiText>{s.folio.bills.map((b:any)=><tr key={b.department+b.id}><td colSpan={5}><div className="bill-heading"><b><UiText>{b.department}</UiText> · <UiText>{b.id}</UiText></b><span><UiText>{b.status}</UiText></span></div><table><tbody><UiText>{b.items.map((i:any,n:number)=><tr key={n}><td><UiText>{i[0]}</UiText></td><td><UiText>{i[1]}</UiText></td><td><UiText>{money(Math.round(i[2]*100))}</UiText></td><td><UiText>{i[3]||0}</UiText>%</td><td><UiText>{money(b.status==='Cancelled'?0:Math.round(i[2]*100*(1-(i[3]||0)/100)))}</UiText></td></tr>)}</UiText></tbody></table><p className="bill-subtotal"><UiText>Bill total: </UiText><UiText>{money(b.totalCents)}</UiText></p></td></tr>)}</UiText></tbody></table><section className="bill-totals"><p><UiText>Total charges </UiText><b><UiText>{money(s.folio.totalCents)}</UiText></b></p><p><UiText>Payments received </UiText><b><UiText>{money(s.folio.paidCents)}</UiText></b></p><h2><UiText>Balance due </UiText><b><UiText>{money(s.folio.balanceCents)}</UiText></b></h2></section><h3><UiText>Payments</UiText></h3><p><UiText>Opening payments: </UiText><UiText>{money(s.initialPaid)}</UiText></p><UiText>{s.payments.map((p:any)=><p key={p.id}><UiText>{p.date.slice(0,10)}</UiText> · <UiText>{p.method}</UiText> · <UiText>{p.reference}</UiText> · <UiText>{money(p.cents)}</UiText></p>)}</UiText><footer><UiText>Thank you for choosing Nirili Villa.</UiText><br/><UiText>Arrive as a guest, leave as a friend.</UiText></footer></main>}catch{return <main><UiText>Could not load your bill. Please reload to retry.</UiText></main>}}
