"use client";
import {useEffect,useMemo,useState} from "react";

const money=(c:number)=>"$"+(Math.max(0,Number(c)||0)/100).toFixed(2);
const discount=(c:number,p:number)=>Math.max(0,Math.round(c*(100-Math.max(0,Math.min(100,p||0)))/100));
const fallback:any={'Bed & Breakfast':[5000,6000,7000],'Half Board':[7000,8000,9000],'Full Board':[8000,10000,12000]};

export default function TourOperatorSite(){
 const [operator,setOperator]=useState<any>(null),[data,setData]=useState<any>(null),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 const [login,setLogin]=useState({username:"",password:""});
 const [form,setForm]=useState<any>({guest:"",phone:"",email:"",checkIn:"",checkOut:"",adults:2,children:0,roomType:"",meal:"",addExcursions:false,excursionIds:[],transfer:"none",packageName:"",notes:""});
 async function load(){try{const s=await fetch("/api/tour-operator-portal/session",{cache:"no-store"}),sd=await s.json();if(!sd.operator){setOperator(null);setData(null);return}setOperator(sd.operator);const r=await fetch("/api/tour-operator-portal/catalog",{cache:"no-store"}),d=await r.json();if(!r.ok)throw Error(d.error);setData(d);}catch(e){setMessage((e as Error).message)}}
 useEffect(()=>{void load()},[]);
 async function signIn(e:React.FormEvent){e.preventDefault();setBusy(true);setMessage("");try{const r=await fetch("/api/tour-operator-portal/session",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(login)}),d=await r.json();if(!r.ok)throw Error(d.error);setOperator(d.operator);await load()}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}}
 async function signOut(){await fetch("/api/tour-operator-portal/session",{method:"DELETE"});setOperator(null);setData(null)}
 const pax=Number(form.adults)+Number(form.children),nights=form.checkIn&&form.checkOut?Math.max(0,(Date.parse(form.checkOut)-Date.parse(form.checkIn))/86400000):0;
 const rates=data?.roomRates||fallback,planRates=rates[form.meal]||fallback[form.meal]||[];
 const roomPublic=nights*(Number(planRates[Math.max(0,Math.min(2,pax-1))])||0),roomNet=discount(roomPublic,operator?.roomDiscountPercent||0);
 const chosen=(data?.excursions||[]).filter((x:any)=>form.excursionIds.includes(x.id));
 const excPublic=chosen.reduce((s:number,x:any)=>s+x.cents*(x.pricingUnit==="couple"?Math.ceil(pax/2):pax),0),excNet=discount(excPublic,operator?.excursionDiscountPercent||0);
 const legs=form.transfer==="return"?2:form.transfer==="arrival"?1:0,transferPublic=(data?.airportTransferCents||3000)*pax*legs,transferNet=discount(transferPublic,operator?.transferDiscountPercent||0);
 const total=roomNet+excNet+transferNet;
 async function book(e:React.FormEvent){e.preventDefault();setBusy(true);setMessage("");try{const r=await fetch("/api/tour-operator-portal/catalog",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"book-package",...form})}),d=await r.json();if(!r.ok)throw Error(d.error);setMessage("Booking "+d.id+" sent to Nirili Villa. Total payable to hotel: "+money(d.totalCents));setForm((x:any)=>({...x,guest:"",phone:"",email:"",packageName:"",notes:"",excursionIds:[]}));await load()}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}}
 if(!operator)return <main className="to-shell"><section className="to-login"><small>NIRILI VILLA · DHIFFUSHI</small><h1>Tour Operator Portal</h1><p>Sign in with the account created by Nirili Villa.</p>{message&&<p className="to-message">{message}</p>}<form onSubmit={signIn}><label>Username<input required value={login.username} onChange={e=>setLogin({...login,username:e.target.value.toLowerCase()})}/></label><label>Password<input required type="password" value={login.password} onChange={e=>setLogin({...login,password:e.target.value})}/></label><button disabled={busy}>{busy?"Signing in…":"Sign in"}</button></form></section></main>;
 return <main className="to-shell"><header className="to-top"><div><small>NIRILI VILLA · TOUR OPERATOR</small><h1>{operator.name}</h1><p>Your contracted net rates are applied automatically.</p></div><button onClick={signOut}>Sign out</button></header>
  <section className="to-discounts"><article><small>Room discount</small><b>{operator.roomDiscountPercent}%</b></article><article><small>Excursion discount</small><b>{operator.excursionDiscountPercent}%</b></article><article><small>Airport transfer discount</small><b>{operator.transferDiscountPercent}%</b></article></section>
  {message&&<p className="to-message">{message}</p>}
  <form className="to-builder" onSubmit={book}>
   <h2>Create guest package & room booking</h2>
   <div className="to-grid"><label>Guest name<input required value={form.guest} onChange={e=>setForm({...form,guest:e.target.value})}/></label><label>WhatsApp<input required placeholder="+960..." value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label>Email<input required type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>Package name (optional)<input value={form.packageName} onChange={e=>setForm({...form,packageName:e.target.value})}/></label></div>
   <div className="to-grid"><label>Check-in<input required type="date" min={data?.today} value={form.checkIn} onChange={e=>setForm({...form,checkIn:e.target.value})}/></label><label>Check-out<input required type="date" min={form.checkIn||data?.today} value={form.checkOut} onChange={e=>setForm({...form,checkOut:e.target.value})}/></label><label>Adults<select value={form.adults} onChange={e=>setForm({...form,adults:Number(e.target.value)})}>{[1,2,3].map(n=><option key={n}>{n}</option>)}</select></label><label>Children<select value={form.children} onChange={e=>setForm({...form,children:Number(e.target.value)})}>{[0,1,2].map(n=><option key={n}>{n}</option>)}</select></label></div>
   <section className="to-step"><h3>1. Select room type</h3><div className="to-choices">{(data?.roomTypes||[]).map((x:string)=><button type="button" key={x} className={form.roomType===x?"active":""} onClick={()=>setForm({...form,roomType:x,meal:""})}>{x}</button>)}</div></section>
   {form.roomType&&<section className="to-step"><h3>2. Select meal plan</h3><div className="to-choices">{(data?.plans||[]).map((x:string)=><button type="button" key={x} className={form.meal===x?"active":""} onClick={()=>setForm({...form,meal:x})}>{x}</button>)}</div></section>}
   {form.meal&&<section className="to-step"><h3>3. Add excursions?</h3><div className="to-choices"><button type="button" className={form.addExcursions?"active":""} onClick={()=>setForm({...form,addExcursions:true})}>Yes, add excursions</button><button type="button" className={!form.addExcursions?"active":""} onClick={()=>setForm({...form,addExcursions:false,excursionIds:[]})}>No excursions</button></div>{form.addExcursions&&<div className="to-excursions">{(data?.excursions||[]).map((x:any)=>{const on=form.excursionIds.includes(x.id);return <button type="button" className={on?"active":""} key={x.id} onClick={()=>setForm({...form,excursionIds:on?form.excursionIds.filter((id:string)=>id!==x.id):[...form.excursionIds,x.id]})}><span>{on?"✓ ":""}{x.name}</span><b>{money(x.cents)} / {x.pricingUnit}</b></button>})}</div>}</section>}
   {form.meal&&<section className="to-step"><h3>4. Airport transfer</h3><div className="to-choices"><button type="button" className={form.transfer==="none"?"active":""} onClick={()=>setForm({...form,transfer:"none"})}>No transfer</button><button type="button" className={form.transfer==="arrival"?"active":""} onClick={()=>setForm({...form,transfer:"arrival"})}>Arrival only</button><button type="button" className={form.transfer==="return"?"active":""} onClick={()=>setForm({...form,transfer:"return"})}>Return transfer</button></div></section>}
   <label>Notes<textarea rows={3} value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label>
   <aside className="to-quote"><h3>Total payable to Nirili Villa</h3><div><span>Room after {operator.roomDiscountPercent}% discount</span><b>{money(roomNet)}</b></div><div><span>Excursions after {operator.excursionDiscountPercent}% discount</span><b>{money(excNet)}</b></div><div><span>Airport transfer after {operator.transferDiscountPercent}% discount</span><b>{money(transferNet)}</b></div><strong><span>Total</span><b>{money(total)}</b></strong><small>Public value {money(roomPublic+excPublic+transferPublic)} · {nights||0} night{nights===1?"":"s"} · {pax} guest{pax===1?"":"s"}</small></aside>
   <button className="to-submit" disabled={busy||!form.roomType||!form.meal||pax>3||pax<1}>{busy?"Creating booking…":"Book room & create package"}</button>
  </form>
  <section className="to-bookings"><h2>My bookings</h2>{!(data?.bookings||[]).length?<p>No bookings yet.</p>:(data.bookings||[]).map((b:any)=><article key={b.id}><div><b>{b.guest}</b><small>{b.id} · {b.checkIn} → {b.checkOut} · {b.meal}</small></div><div><strong>{money(b.estimate)}</strong><span>{b.status}{b.room?" · Room "+b.room:""}</span></div></article>)}</section>
 </main>;
}
