'use client';
import Link from 'next/link';
import {startLiveRefresh,REFRESH_INTERVALS} from '../../../../lib/live-refresh';
import {useEffect,useState} from 'react';
import {ArrowLeft,CalendarDays,CheckCircle2,Clock3,MapPin,Plus,ShieldCheck,ShipWheel,Trash2,Users,XCircle} from 'lucide-react';

type Guest={name:string;ageCategory:'adult'|'child'|'infant';footSize:string};
const money=(cents:number)=>'$'+(Math.max(0,Number(cents)||0)/100).toFixed(2);
const guest=():Guest=>({name:'',ageCategory:'adult',footSize:''});

export default function ManageExcursionSite(){
 const [token,setToken]=useState(''),[booking,setBooking]=useState<any>(null),[items,setItems]=useState<any[]>([]),[form,setForm]=useState<any>({}),[guests,setGuests]=useState<Guest[]>([guest()]);
 const [ready,setReady]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 const selected=items.find(item=>item.id===form.menuItemId);
 function sync(value:any){
  setForm({menuItemId:value.menuItemId,date:value.date,email:value.email,phone:value.phone,hotel:value.hotel,externalRoom:value.room,groupName:value.groupName||'',buggyRequested:!!value.buggyRequested,privateBoatRequested:!!value.privateBoatRequested,notes:value.notes||''});
  const names=value.guestNames||[],categories=value.guestCategories||[],sizes=value.footSizes||[];
  setGuests(Array.from({length:Math.max(1,value.quantity||names.length||1)},(_,i)=>({name:names[i]||(i===0?value.guest:''),ageCategory:categories[i]||'adult',footSize:sizes[i]?String(sizes[i]):''})));
 }
 async function call(action:string,payload:any={}){
  const r=await fetch('/api/public-excursions/manage',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,token,...payload}),cache:'no-store'});
  const d=await r.json();if(!r.ok)throw Error(d.error||'Could not manage this excursion.');return d;
 }
 useEffect(()=>{const value=decodeURIComponent(window.location.hash.replace(/^#/,'').trim());setToken(value);if(!value){setError('This manage-excursion link is incomplete. Open the private link from your Nirili Tours email.');setReady(true);return;}fetch('/api/public-excursions/manage',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'view',token:value}),cache:'no-store'}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error||'Could not load excursion.');setBooking(d.booking);setItems(d.items||[]);sync(d.booking)}).catch(e=>setError(e.message)).finally(()=>setReady(true));},[]);
 const needsFeet=!!selected?.needsFootSizes,adults=guests.filter(g=>g.ageCategory==='adult').length,children=guests.filter(g=>g.ageCategory==='child').length,infants=guests.filter(g=>g.ageCategory==='infant').length;
 function updateGuest(index:number,patch:Partial<Guest>){setGuests(list=>list.map((g,i)=>i===index?{...g,...patch}:g));}
 function addGuest(){setGuests(list=>list.length>=20?list:[...list,guest()]);}
 function removeGuest(index:number){setGuests(list=>list.length<=1?list:list.filter((_,i)=>i!==index));}
 useEffect(()=>{
  if(!token||!ready||busy)return;
  const controller=new AbortController();
  const stop=startLiveRefresh(async()=>{
   const response=await fetch('/api/public-excursions/manage',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'view',token}),cache:'no-store',signal:controller.signal});
   const result=await response.json();
   if(response.ok&&!controller.signal.aborted)setBooking(result.booking);
  },REFRESH_INTERVALS.guest);
  return()=>{stop();controller.abort();};
 },[token,ready,busy]);
 async function save(e:React.FormEvent){e.preventDefault();if(busy)return;setBusy(true);setError('');setMessage('');try{const payload={...form,guest:guests[0]?.name||'',guestNames:guests.map(g=>g.name),guestCategories:guests.map(g=>g.ageCategory),footSizes:needsFeet?guests.map(g=>Number(g.footSize)):[],privateBoatRequested:form.privateBoatRequested&&guests.length>=4};const d=await call('update',payload);setBooking(d.booking);setItems(d.items||items);sync(d.booking);setMessage(d.applied?'Your excursion booking was updated.':'Your change request was sent to the Nirili Tours team. Your current confirmed trip stays active until it is approved.');}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function cancel(){if(busy||!booking?.canCancel)return;if(!window.confirm(booking.status==='Pending'?'Cancel this pending excursion booking?':'Request cancellation of this excursion? Your confirmed trip remains active until our team approves it.'))return;setBusy(true);setError('');setMessage('');try{const d=await call('cancel');setBooking(d.booking);sync(d.booking);setMessage(d.cancelled?'Your excursion booking has been cancelled.':'Your cancellation request was sent to Nirili Tours. Your current booking remains active until it is approved.');}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 if(!ready)return <div className="manage-excursion"><section className="manage-card">Loading your excursion…</section></div>;
 if(error&&!booking)return <div className="manage-excursion"><section className="manage-card error-card"><XCircle/><h1>We couldn’t open this excursion.</h1><p>{error}</p><Link href="/"><ArrowLeft/> Back to excursions</Link></section></div>;
 const pending=booking.pendingAction,isPackage=Array.isArray(booking.packageSegments)&&booking.packageSegments.length>1;
 return <div className="manage-excursion">
  <section className="manage-hero"><div><span className="eyebrow">MY EXCURSION</span><h1>{booking.excursion}</h1><p>Live booking status, departure details, payment and passenger information.</p></div><div className="reference"><small>BOOKING REFERENCE</small><strong>{booking.reference}</strong><span>{booking.status}</span></div></section>
  {(message||error)&&<p className={'manage-message '+(error?'error':'success')}>{error||message}</p>}
  {pending&&<section className="pending-banner"><CheckCircle2/><div><strong>{pending.type==='cancel'?'Cancellation requested':'Change requested'}</strong><p>Your current confirmed excursion remains active while our team reviews this request.</p><small>{pending.id} · {new Date(pending.requestedAt).toLocaleString('en-GB',{timeZone:'Indian/Maldives',hour12:false})}</small></div></section>}
  <section className="status-grid">
   <article><CalendarDays/><div><small>{isPackage?'PACKAGE START':'DATE'}</small><strong>{booking.date}</strong></div></article><article><Clock3/><div><small>{isPackage?'TRIPS':'DEPARTURE'}</small><strong>{isPackage?booking.packageSegments.length+' scheduled':(booking.time||'To be confirmed')}</strong></div></article><article><MapPin/><div><small>PICKUP</small><strong>{booking.hotel}{booking.room?' · Room '+booking.room:''}</strong></div></article><article><ShipWheel/><div><small>VESSEL</small><strong>{booking.vessel||'To be assigned'}</strong></div></article><article><Users/><div><small>GUESTS</small><strong>{booking.quantity}</strong></div></article><article><ShieldCheck/><div><small>PAYMENT</small><strong>{booking.paymentStatus}</strong><span>{booking.balanceCents?money(booking.balanceCents)+' balance':'No balance shown'}</span></div></article>
  </section>
  {isPackage&&<section className="package-itinerary"><div className="package-itinerary-head"><span className="eyebrow">SPECIAL PACKAGE ITINERARY</span><h2>Your scheduled departures</h2><p>These trips together cover the activities included in your Special Package.</p></div><div className="package-itinerary-list">{booking.packageSegments.map((segment:any,index:number)=><article key={segment.id}><b>{index+1}</b><div><strong>{segment.name}</strong><p>{segment.date} · {segment.time}{segment.endTime?'–'+segment.endTime:''} · Maldives time</p>{segment.matchedScheduleName&&segment.matchedScheduleName!==segment.name&&<small>Scheduled on: {segment.matchedScheduleName}</small>}<small>{segment.vessel?'Vessel: '+segment.vessel:'Vessel assignment may update before departure'}{segment.crew?.length?' · Crew: '+segment.crew.join(', '):''}</small></div><span><em>{segment.approvalStatus==='Approved'?'Confirmed':segment.approvalStatus||segment.status}</em><small>{segment.paymentStatus}</small></span></article>)}</div></section>}
  {booking.status==='Cancelled'?<section className="cancelled-card"><XCircle/><div><h2>Excursion cancelled</h2><p>This booking is no longer active.</p>{booking.refundRequiredCents>0&&<p><strong>Refund required: {money(booking.refundRequiredCents)}</strong><br/>The Nirili Tours team will handle this separately.</p>}</div></section>:
  <section className="manage-grid"><form className="edit-card" onSubmit={save}><span className="eyebrow">BOOKING DETAILS</span><h2>{isPackage?'Package guest details':'View or request changes'}</h2><p>{isPackage?'Your package departures are linked together. Contact Nirili Tours if you need to change an individual package trip; this page keeps those scheduled seats protected.':booking.status==='Pending'?'Unscheduled details can be updated before confirmation when no payment has been recorded.':'Confirmed-trip changes are reviewed by the excursions team before affecting your schedule.'}</p>
   <label>Excursion<select disabled={!booking.canEdit||busy} value={form.menuItemId||''} onChange={e=>setForm({...form,menuItemId:e.target.value,privateBoatRequested:false})}>{items.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label>
   <div className="two"><label>Date<input required type="date" disabled={!booking.canEdit||busy} value={form.date||''} onChange={e=>setForm({...form,date:e.target.value})}/></label><label>Email<input required type="email" disabled={!booking.canEdit||busy} value={form.email||''} onChange={e=>setForm({...form,email:e.target.value})}/></label></div>
   <div className="two"><label>WhatsApp<input required type="tel" disabled={!booking.canEdit||busy} value={form.phone||''} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label>Hotel / pickup<input required disabled={!booking.canEdit||busy} value={form.hotel||''} onChange={e=>setForm({...form,hotel:e.target.value})}/></label></div>
   <div className="two"><label>Room number<input disabled={!booking.canEdit||busy} value={form.externalRoom||''} onChange={e=>setForm({...form,externalRoom:e.target.value})}/></label><label>Family / group name<input disabled={!booking.canEdit||busy} value={form.groupName||''} onChange={e=>setForm({...form,groupName:e.target.value})}/></label></div>
   <div className="passenger-head"><div><strong>Passengers</strong><small>{adults} adult · {children} child · {infants} under 3</small></div><button type="button" disabled={!booking.canEdit||busy||guests.length>=20} onClick={addGuest}><Plus/> Add guest</button></div>
   <div className="passengers">{guests.map((g,i)=><div className="passenger" key={i}><b>{i+1}</b><label>Name<input required disabled={!booking.canEdit||busy} value={g.name} onChange={e=>updateGuest(i,{name:e.target.value})}/></label><label>Age<select disabled={!booking.canEdit||busy} value={g.ageCategory} onChange={e=>updateGuest(i,{ageCategory:e.target.value as Guest['ageCategory']})}><option value="adult">Adult (12+)</option><option value="child">Child (3–11)</option><option value="infant">Under 3</option></select></label>{needsFeet&&<label>EU foot size<input required type="number" min={15} max={50} disabled={!booking.canEdit||busy} value={g.footSize} onChange={e=>updateGuest(i,{footSize:e.target.value})}/></label>}<button type="button" disabled={!booking.canEdit||busy||guests.length===1} onClick={()=>removeGuest(i)}><Trash2/></button></div>)}</div>
   {guests.length>=4&&<label className="check"><span><input type="checkbox" disabled={!booking.canEdit||busy} checked={!!form.privateBoatRequested} onChange={e=>setForm({...form,privateBoatRequested:e.target.checked})}/> Request private boat (+$50)</span></label>}
   <label className="check"><span><input type="checkbox" disabled={!booking.canEdit||busy} checked={!!form.buggyRequested} onChange={e=>setForm({...form,buggyRequested:e.target.checked})}/> Request buggy pickup</span></label>
   <label>Notes<textarea rows={4} maxLength={1000} disabled={!booking.canEdit||busy} value={form.notes||''} onChange={e=>setForm({...form,notes:e.target.value})}/></label>
   <button className="primary" disabled={!booking.canEdit||busy}>{busy?'Saving…':booking.status==='Pending'?'Update Excursion':'Request Changes'}</button>
  </form>
  <aside className="side-card"><div><small>BOOKING VALUE</small><strong>{money(booking.quotedCents)}</strong><span>{booking.paymentStatus}</span></div>{booking.time&&<div><h3>Trip details</h3><p>Departure {booking.time}{booking.endTime?' · expected end '+booking.endTime:''}{booking.returnTime?' · return pickup '+booking.returnTime:''}. Maldives time.</p></div>}<div className="cancel-zone"><h3>Need to cancel?</h3><p>{isPackage?'Cancellation applies to the entire Special Package and all linked departures. Our team reviews it before releasing the package seats.':booking.status==='Pending'?'An unpaid unscheduled request can be cancelled immediately.':'A confirmed or paid excursion cancellation is reviewed by the Nirili Tours team.'}</p><button className="danger" type="button" disabled={!booking.canCancel||busy} onClick={cancel}>{isPackage?'Request Package Cancellation':booking.status==='Pending'?'Cancel Excursion':'Request Cancellation'}</button></div><p className="security"><ShieldCheck/> This private link controls your excursion. Do not forward it.</p></aside></section>}
 </div>;
}
