'use client';
import {useState} from 'react';
import {ArrowRight,Eye,EyeOff,KeyRound} from 'lucide-react';
import AuthShell from '../auth-shell';
import {UiField,UiText} from '../ui-language';
export default function GuestStayLogin(){
 const [username,setUsername]=useState(''),[password,setPassword]=useState(''),[show,setShow]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function submit(e:React.FormEvent){e.preventDefault();if(busy)return;setBusy(true);setError('');try{const r=await fetch('/api/guest-auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username,password})}),d=await r.json();if(!r.ok)throw Error(d.error||'Could not sign in.');window.location.assign('/stay');}catch(e){setError((e as Error).message);setBusy(false);}}
 return <AuthShell><div className="nv-auth-heading"><span className="nv-eyebrow"><UiText>NIRILI VILLA · GUEST STAY</UiText></span><h2><UiText>Guest portal</UiText></h2><p><UiText>Use the room number and five-digit password given to you after check-in.</UiText></p></div><div className="nv-direct-login-badge"><KeyRound size={20}/><div><small><UiText>ACCESS</UiText></small><strong><UiText>In-house guest</UiText></strong></div></div><form className="nv-login-form" onSubmit={submit}><label><UiText>Room number</UiText><UiField as="input" required inputMode="numeric" pattern="[0-9]*" autoComplete="username" value={username} onChange={e=>setUsername(e.target.value.replace(/\D/g,'').slice(0,10))} placeholder="e.g. 201"/></label><label><UiText>Guest password</UiText><span className="nv-password"><UiField as="input" required type={show?'text':'password'} inputMode="numeric" pattern="[0-9]*" autoComplete="current-password" maxLength={5} value={password} onChange={e=>setPassword(e.target.value.replace(/\D/g,'').slice(0,5))} placeholder="5 digits"/><UiField as="button" type="button" aria-label={show?'Hide password':'Show password'} onClick={()=>setShow(!show)}><UiText>{show?<EyeOff size={20}/>:<Eye size={20}/>}</UiText></UiField></span></label>{error&&<p className="nv-login-error" role="alert"><UiText>{error}</UiText></p>}<button className="nv-submit" disabled={busy}><UiText>{busy?'Signing in…':'Open my stay'}</UiText><ArrowRight size={18}/></button><p className="nv-phone-note"><UiText>Your guest login is active only while you are checked in. It cannot open the Nirili management system.</UiText></p></form></AuthShell>;
}
