
import {UiText,UiField,UiOption} from '../../../ui-language';
import {tableLabel} from '../../../../lib/restaurant-tables';
import {tabRedirect} from '../../../../lib/tab-session';
import {currentUser} from '../../../../lib/auth';
import {canPOS} from '../../../../lib/pos-access';
import {loadStays} from '../../../../lib/stays';
import ReceiptPrint from './print';
import './receipt.css';
export const dynamic='force-dynamic';
const money=(n:number)=>'$'+(n/100).toFixed(2);
export default async function Receipt({params}:{params:Promise<{id:string}>}){const u=await currentUser();if(!u)await tabRedirect('/login?portal=staff&returnTo=%2Frestaurant');if(!canPOS(u))return <main><UiText>Restaurant access required.</UiText></main>;const {id}=await params,{state}=await loadStays();const o=state.posOrders?.find((o:any)=>o.id===id);if(!o)return <main><UiText>Bill not found.</UiText></main>;const stay=state.stays.find((s:any)=>s.id===o.stayId);const paid=o.method==='Cash'||o.method==='Card'||stay?.paidBills?.['Restaurant:'+o.id]===o.cents;const status=o.complimentary?'Complimentary':paid?'Paid':o.method==='Room'?'Charged to room':'Unpaid';return <main className="receipt-page"><ReceiptPrint/><article className="restaurant-receipt"><header><small><UiText>DHIFFUSHI · MALDIVES</UiText></small><h1><UiText>NIRILI VILLA</UiText></h1><p><UiText>RESTAURANT INVOICE</UiText></p><b><UiText>{o.id}</UiText></b></header><div className="receipt-meta"><p><span><UiText>Customer</UiText></span><b>{o.customer}</b></p><UiText>{o.room&&<p><span><UiText>Room</UiText></span><b><UiText>{o.room}</UiText></b></p>}</UiText><p><span><UiText>Table</UiText></span><b><UiText>{tableLabel(o.table)}</UiText></b></p><p><span><UiText>Issued</UiText></span><b><UiText>{new Intl.DateTimeFormat('en-GB',{timeZone:'Indian/Maldives',dateStyle:'medium',timeStyle:'short'}).format(new Date(o.createdAt))}</UiText></b></p><p><span><UiText>Cashier</UiText></span><b><UiText>{o.createdBy}</UiText></b></p></div><table><thead><tr><th><UiText>Item / quantity</UiText></th><th><UiText>USD</UiText></th></tr></thead><tbody><UiText>{o.items.map((i:any,n:number)=><tr key={n}><td><UiText>{i.name}</UiText><small><UiText>{i.quantity}</UiText> × <UiText>{money(i.unitCents)}</UiText></small><UiText>{i.discount>0&&<small style={{display:"block"}}><UiText>Discount </UiText><UiText>{i.discount}</UiText>%</small>}</UiText></td><td><UiText>{money(i.cents)}</UiText></td></tr>)}</UiText></tbody></table><div className="receipt-totals"><p className="receipt-grand"><span><UiText>Total USD</UiText></span><b><UiText>{money(o.cents)}</UiText></b></p><p><span><UiText>Paid</UiText></span><b><UiText>{money(paid?o.cents:0)}</UiText></b></p><p><span><UiText>Balance</UiText></span><b><UiText>{money(paid?0:o.cents)}</UiText></b></p><p><span><UiText>Payment</UiText></span><b><UiText>{o.complimentary?'Complimentary':o.method==='Room'?'Room charge':o.method||'Not received'}</UiText></b></p><strong className="receipt-status"><UiText>{status}</UiText></strong></div><footer><p><UiText>Thank you for dining with us.</UiText></p><small><UiText>Arrive as a guest, leave as a friend.</UiText></small></footer></article></main>;}
