import {tableLabel} from '../../../../lib/restaurant-tables';
import {tabRedirect} from '../../../../lib/tab-session';
import {currentUser} from '../../../../lib/auth';
import {canPOS} from '../../../../lib/pos-access';
import {loadStays} from '../../../../lib/stays';
import ReceiptPrint from './print';
import './receipt.css';
export const dynamic='force-dynamic';
const money=(n:number)=>'$'+(n/100).toFixed(2);
export default async function Receipt({params}:{params:Promise<{id:string}>}){const u=await currentUser();if(!u)await tabRedirect('/login?portal=staff&returnTo=%2Frestaurant');if(!canPOS(u))return <main>Restaurant access required.</main>;const {id}=await params,{state}=await loadStays();const o=state.posOrders?.find((o:any)=>o.id===id);if(!o)return <main>Bill not found.</main>;const stay=state.stays.find((s:any)=>s.id===o.stayId);const paid=o.method==='Cash'||o.method==='Card'||stay?.paidBills?.['Restaurant:'+o.id]===o.cents;const status=o.complimentary?'Complimentary':paid?'Paid':o.method==='Room'?'Charged to room':'Unpaid';return <main className="receipt-page"><ReceiptPrint/><article className="restaurant-receipt"><header><small>DHIFFUSHI · MALDIVES</small><h1>NIRILI VILLA</h1><p>RESTAURANT INVOICE</p><b>{o.id}</b></header><div className="receipt-meta"><p><span>Customer</span><b>{o.customer}</b></p>{o.room&&<p><span>Room</span><b>{o.room}</b></p>}<p><span>Table</span><b>{tableLabel(o.table)}</b></p><p><span>Issued</span><b>{new Intl.DateTimeFormat('en-GB',{timeZone:'Indian/Maldives',dateStyle:'medium',timeStyle:'short'}).format(new Date(o.createdAt))}</b></p><p><span>Cashier</span><b>{o.createdBy}</b></p></div><table><thead><tr><th>Item / quantity</th><th>USD</th></tr></thead><tbody>{o.items.map((i:any,n:number)=><tr key={n}><td>{i.name}<small>{i.quantity} × {money(i.unitCents)}</small>{i.discount>0&&<small style={{display:"block"}}>Discount {i.discount}%</small>}</td><td>{money(i.cents)}</td></tr>)}</tbody></table><div className="receipt-totals"><p className="receipt-grand"><span>Total USD</span><b>{money(o.cents)}</b></p><p><span>Paid</span><b>{money(paid?o.cents:0)}</b></p><p><span>Balance</span><b>{money(paid?0:o.cents)}</b></p><p><span>Payment</span><b>{o.complimentary?'Complimentary':o.method==='Room'?'Room charge':o.method||'Not received'}</b></p><strong className="receipt-status">{status}</strong></div><footer><p>Thank you for dining with us.</p><small>Arrive as a guest, leave as a friend.</small></footer></article></main>;}
