'use client';
import {useEffect,useRef,useState} from 'react';
import {printThermalReceipt} from '../../../../lib/thermal-print';
import {directThermalPrint,thermalPrinters} from '../../../../lib/direct-thermal';
export default function ReceiptPrint(){const started=useRef(false),printing=useRef(false),[message,setMessage]=useState(''),[printer,setPrinter]=useState(''),[printers,setPrinters]=useState<string[]>([]),[busy,setBusy]=useState(false),[remember,setRemember]=useState(false);
 async function print(direct=false,name=printer){if(printing.current)return;printing.current=true;setBusy(true);setMessage('');try{if(direct){await directThermalPrint(name);setMessage('Receipt sent to '+name+'. Check the printer before retrying.');}else{const height=await printThermalReceipt();setMessage('Browser receipt: 58 × '+height+' mm. Driver paper settings may add blank space.');}}catch(e){setMessage((e as Error).message+' If direct printing cannot connect, install and start QZ Tray, then choose Connect printer.');}finally{printing.current=false;setBusy(false);}}
 async function connect(){setBusy(true);setMessage('');try{const names=await thermalPrinters();setPrinters(names);const selected=names.includes(printer)?printer:names.find(n=>n==='581PW')||names.find(n=>n.includes('581'))||'';setPrinter(selected);setMessage('Connected. Select your 58 mm printer and click Direct thermal print.');}catch(e){setMessage('Could not connect. Install and open QZ Tray on this computer, then retry. '+(e as Error).message)}finally{setBusy(false)}}
 useEffect(()=>{let cancelled=false;async function start(){await document.fonts.ready;if(cancelled||started.current)return;started.current=true;let saved='';try{saved=localStorage.getItem('nirili-thermal-printer')||'';}catch{}if(saved){setPrinter(saved);setRemember(true);await print(true,saved);}}start();return()=>{cancelled=true}},[]);
 return <nav className="receipt-controls"><a href="/restaurant">← Restaurant</a><button disabled={busy} onClick={connect}>Connect printer</button>{(printers.length>0||printer)&&<label>58 mm printer<select disabled={busy} value={printer} onChange={e=>{setPrinter(e.target.value);setRemember(false);try{localStorage.removeItem('nirili-thermal-printer')}catch{}}}><option value="">Select printer</option>{[...new Set([...printers,...(printer?[printer]:[])])].map(p=><option key={p}>{p}</option>)}</select></label>}<button disabled={busy||!printer} onClick={()=>print(true)}>Direct thermal print</button>{printer&&<label><input type="checkbox" checked={remember} onChange={e=>{setRemember(e.target.checked);try{if(e.target.checked)localStorage.setItem('nirili-thermal-printer',printer);else localStorage.removeItem('nirili-thermal-printer');setMessage(e.target.checked?'Future Print Bill clicks will use '+printer+'.':'Automatic direct printing disabled.');}catch{setMessage('This browser could not save the printer.');}}}/> Use this printer automatically for future bills</label>}<button disabled={busy} onClick={()=>print(false)}>Browser print / PDF</button><p>For variable-length receipts, install and open <a href="https://qz.io/download/" target="_blank" rel="noopener noreferrer">QZ Tray for Windows</a>, connect, and select 581PW. Direct printing requires an ESC/POS-compatible printer. Approve QZ’s connection/print prompts when requested. Browser printing may still feed the full paper size.</p>{message&&<p role="status">{message}</p>}</nav>;
}
