import {credentialStatement,mirrorCredentialRecord} from '../../../lib/credential-store';
import {authDb,currentUser,hashPassword,sameOrigin,validPassword} from '../../../lib/auth';
import {loadStays,stayKey} from '../../../lib/stays';
import {mirrorHotelState,mirrorLegacyAccount,mirrorOperationalRecord} from '../../../lib/supabase-bridge';
export async function GET(r:Request){if((await currentUser())?.role!=='admin')return Response.json({error:'Admin access required'},{status:403});const {state,revision}=await loadStays();const s=state.stays.find((s:any)=>s.id===new URL(r.url).searchParams.get('stay'));const account=s?.accountId?await authDb().prepare("SELECT id,username,name,role,active FROM accounts WHERE id=? AND role='guest'").bind(s.accountId).first():null;if(account){(account as any).stays=[{id:s.id,room:s.room,meal:s.meal,status:s.status}];}return Response.json({canCreate:true,account,revision,stays:state.stays.filter((s:any)=>!s.accountId&&['Confirmed','In House'].includes(s.status)).map((s:any)=>({id:s.id,room:s.room,guest:s.guest,meal:s.meal}))},{headers:{'Cache-Control':'no-store'}});}
export async function POST(r:Request){const u=await currentUser();if(u?.role!=='admin'||!sameOrigin(r))return Response.json({error:'Admin access required'},{status:403});try{const b=await r.json(),{state,revision}=await loadStays();const s=state.stays.find((s:any)=>s.id===b.stayId);if(!s||!['Confirmed','In House'].includes(s.status))throw Error('Select a confirmed or checked-in booking.');if(s.accountId)throw Error('This booking already has a guest account.');if(b.revision!==revision)throw Error('Booking changed. Reopen the form and try again.');if(b.room!==s.room||typeof b.name!=='string'||!b.name.trim()||b.name.length>100||!['Bed & Breakfast','Half Board','Full Board'].includes(b.meal))throw Error('Select a room, guest name and meal type.');const previous={guest:s.guest,meal:s.meal};s.guest=b.name.trim();s.meal=b.meal;const username=String(b.username||'').trim().toLowerCase();if(!/^[a-z0-9._-]{3,40}$/.test(username)||!validPassword(b.password))throw Error('Use a username of 3–40 letters/numbers and a password of 8–128 characters.');const id=crypto.randomUUID(),p=await hashPassword(b.password);if(s.legacyFolio!==false)s.legacyFolio=true;s.accountId=id;s.history.unshift({date:new Date().toISOString(),by:u.username,detail:'Guest login created: '+username+' · '+s.meal,previous});const db=authDb();const results=await db.batch([db.prepare("INSERT INTO accounts(id,username,email,name,password_hash,salt,role,permissions,active) SELECT ?,?,NULL,?,?,?,'guest','[]',1 WHERE EXISTS(SELECT 1 FROM operation_records WHERE key=? AND revision=?)").bind(id,username,s.guest,p.hash,p.salt,stayKey,revision),db.prepare('UPDATE operation_records SET payload=?,revision=revision+1,updated_by=? WHERE key=? AND revision=?').bind(JSON.stringify(state),u.userId,stayKey,revision),await credentialStatement(id,p.hash,b.password,u.userId)]);if(!results[0].meta.changes)return Response.json({error:'Booking changed. Refresh and try again.'},{status:409});
try{
 const account=await db.prepare('SELECT * FROM accounts WHERE id=?').bind(id).first<any>();
 await Promise.all([
  account?mirrorLegacyAccount(account):Promise.resolve(false),
  mirrorCredentialRecord(id),
  mirrorHotelState(state),
  mirrorOperationalRecord(stayKey,state,revision+1,u.userId)
 ]);
}catch{}
return Response.json({ok:true,username,room:s.room},{headers:{'Cache-Control':'no-store'}});}catch(e){return Response.json({error:(e as Error).message.includes('UNIQUE')?'Username already exists. Choose another username.':(e as Error).message},{status:400});}}
