import {cookies} from 'next/headers';
import {sessionCookieName} from '../../../lib/tab-session';
import {authDb,randomToken,digest,sameOrigin,limit} from '../../../lib/auth';
import {initialTransport,createTransfer,TransportState} from '../../../lib/transport';
const key='transport-bookings-v1';
async function load(){const row=await authDb().prepare('SELECT payload,revision FROM operation_records WHERE key=?').bind(key).first<any>();return {state:row?JSON.parse(row.payload) as TransportState:initialTransport(),revision:row?.revision||0};}
async function identity(){const name=await sessionCookieName('nirili_transfer'),token=(await cookies()).get(name)?.value;return {name,token:token&&/^[a-f0-9]{64}$/.test(token)?token:null};}
function view(state:TransportState,revision:number,owner:string){return {revision,canEdit:false,isAdmin:false,role:'Walk-in',ownRoom:null,sailings:state.sailings.filter(s=>s.active),bookings:state.bookings.filter(b=>b.owner===owner).map(({owner,token,...b})=>b),availability:state.bookings.filter(b=>b.status!=='Cancelled').flatMap(b=>b.journeys.map(j=>({scheduleId:j.scheduleId,date:j.date,seats:j.seats,pax:b.adults+b.children+b.infants})))};}
export async function GET(){try{const id=await identity(),token=id.token||randomToken(),owner='walk-transfer:'+await digest(token),{state,revision}=await load();return Response.json(view(state,revision,owner),{headers:{'Cache-Control':'no-store',...(!id.token?{'Set-Cookie':`${id.name}=${token}; HttpOnly; Secure; SameSite=Lax; Path=/; Max-Age=43200`}:{})}});}catch{return Response.json({error:'Unable to load transfers. Please refresh.'},{status:503});}}
export async function POST(r:Request){if(!sameOrigin(r))return Response.json({error:'Invalid request.'},{status:403});try{const id=await identity();if(!id.token)throw Error('Refresh before booking.');const owner='walk-transfer:'+await digest(id.token),b=await r.json();if(b.action!=='book'||b.payment!=='later')return Response.json({error:'Walk-in guests can book transfers with payment at reception only.'},{status:403});const {state,revision}=await load();if(state.bookings.some(x=>x.owner===owner&&x.token===b.token))return Response.json(view(state,revision,owner));if(b.revision!==revision)return Response.json({error:'Availability changed. Refresh and review your seats.'},{status:409});if(!await limit(owner,10,3600000)||!await limit('walk-transfer-ip:'+(r.headers.get('cf-connecting-ip')||'unknown'),40,3600000))throw Error('Please contact reception for further bookings.');const booking=createTransfer(state,b,owner);state.bookings.push(booking);const payload=JSON.stringify(state);const saved=revision===0?await authDb().prepare('INSERT OR IGNORE INTO operation_records(key,payload,revision,updated_by) VALUES(?,?,1,?)').bind(key,payload,owner).run():await authDb().prepare('UPDATE operation_records SET payload=?,revision=revision+1,updated_by=? WHERE key=? AND revision=?').bind(payload,owner,key,revision).run();if(!saved.meta.changes)return Response.json({error:'Another booking arrived. Refresh and review your seats.'},{status:409});return Response.json(view(state,revision+1,owner),{headers:{'Cache-Control':'no-store'}});}catch(e){return Response.json({error:(e as Error).message},{status:400});}}
