"use client";
import {useCallback,useEffect,useMemo,useRef,useState} from "react";
import {BatteryCharging,CalendarDays,CarFront,CheckCircle2,MapPin,Plus,RefreshCw,Settings2,ShieldAlert,Trash2,UserRound,Wrench} from "lucide-react";
import {startLiveRefresh,REFRESH_INTERVALS} from "../lib/live-refresh";
import {islandToday} from "../lib/guest-catalog";
import DateFieldDMY from "./date-field-dmy";
import TimeField24 from "./time-field-24";
import {UiText,UiField,UiOption} from "./ui-language";

type Tab="Overview"|"Dispatch"|"Fleet"|"Maintenance"|"Tracking";
const statuses=["Available","Assigned","Charging","Maintenance","Out of Service"];
const emptyBuggy={id:"",name:"",capacity:4,status:"Available",driver:"",driverPhone:"",battery:"",trackerProvider:"",trackerId:"",maintenanceDue:"",notes:""};

export default function BuggyManagementPanel(){
 const [tab,setTab]=useState<Tab>("Overview"),[date,setDate]=useState(islandToday()),[fleet,setFleet]=useState<any[]>([]),[dispatches,setDispatches]=useState<any[]>([]),[upcoming,setUpcoming]=useState<any[]>([]),[maintenance,setMaintenance]=useState<any[]>([]),[history,setHistory]=useState<any[]>([]),[loading,setLoading]=useState(true),[message,setMessage]=useState(""),[busy,setBusy]=useState("");
 const [buggyForm,setBuggyForm]=useState<any>(null),[maintenanceForm,setMaintenanceForm]=useState<any>(null),[manualBooking,setManualBooking]=useState<any>(null),[guestRideFare,setGuestRideFare]=useState("0.00"),[canChangePricing,setCanChangePricing]=useState(false);
 const fareDirty=useRef(false);
 const load=useCallback(async(background=false)=>{if(!background)setLoading(true);try{const r=await fetch("/api/buggy-management?date="+encodeURIComponent(date),{cache:"no-store"}),d=await r.json();if(!r.ok)throw Error(d.error||"Could not load buggy management.");setFleet(d.fleet||[]);setDispatches(d.dispatches||[]);setUpcoming(d.upcoming||[]);setMaintenance(d.maintenance||[]);setHistory(d.history||[]);if(!fareDirty.current)setGuestRideFare((Math.max(0,Number(d.settings?.guestRideFareCents)||0)/100).toFixed(2));setCanChangePricing(d.canChangePricing===true);setMessage("");}catch(e){setMessage(e instanceof Error?e.message:"Could not load buggy management.");}finally{setLoading(false)}},[date]);
 useEffect(()=>{void load();return startLiveRefresh(()=>load(true),REFRESH_INTERVALS.live)},[load]);
 async function action(body:any,success:string){if(busy)return;setBusy(body.action+(body.id||body.buggyId||""));setMessage("");try{const r=await fetch("/api/buggy-management",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}),d=await r.json();if(!r.ok)throw Error(d.error||"Could not save changes.");if(body.action==="save-settings")fareDirty.current=false;setMessage(success);setBuggyForm(null);setMaintenanceForm(null);await load(true);window.dispatchEvent(new Event("services-updated"));}catch(e){setMessage(e instanceof Error?e.message:"Could not save changes.");}finally{setBusy("")}}
 async function createManualBooking(e:React.FormEvent){
  e.preventDefault();if(!manualBooking||busy)return;setBusy("manual-booking");setMessage("");
  try{
   const r=await fetch("/api/buggy-driver",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...manualBooking,bookingType:"manual"})}),d=await r.json();
   if(!r.ok)throw Error(d.error||"Could not create buggy booking.");
   setManualBooking(null);setMessage("Buggy booking created.");await load(true);window.dispatchEvent(new Event("services-updated"));
  }catch(e){setMessage(e instanceof Error?e.message:"Could not create buggy booking.");}
  finally{setBusy("")}
 }
 const activeStatuses=(status:string)=>!["Completed","Round trip complete","Cancelled"].includes(String(status||""));
 const activeJobs=dispatches.filter(x=>activeStatuses(x.status)).length;
 const waitingAssignment=dispatches.filter(x=>activeStatuses(x.status)&&(!x.buggyId||x.status==="Requested")).length;
 const driverOnWay=dispatches.filter(x=>x.status==="Driver on the way").length;
 const arrived=dispatches.filter(x=>["Arrived","Return pickup arrived"].includes(x.status)).length;
 const onTrip=dispatches.filter(x=>["On trip","Boarded","Going to dinner","Returning"].includes(x.status)).length;
 const available=fleet.filter(x=>x.status==="Available").length;
 const maintenanceCount=fleet.filter(x=>["Maintenance","Out of Service"].includes(x.status)).length;
 const trackerCount=fleet.filter(x=>x.trackerId).length;
 const selectedDateLabel=useMemo(()=>date.split("-").reverse().join("-"),[date]);
 const nextAction=(row:any)=>{
  if(row.status==="Requested"||!row.buggyId)return "Assign buggy";
  if(row.status==="Assigned"||row.status==="Pending pickup")return "Driver to depart";
  if(row.status==="Driver on the way")return "En route to guest";
  if(["Arrived","Return pickup arrived"].includes(row.status))return "Waiting for guest";
  if(["On trip","Boarded","Going to dinner","Returning"].includes(row.status))return "Trip in progress";
  if(["Completed","Round trip complete"].includes(row.status))return "Ride completed";
  if(row.status==="Cancelled")return "Cancelled";
  return "Review";
 };
 const liveFleet=fleet.map(b=>{const ride=dispatches.find(x=>x.buggyId===b.id&&activeStatuses(x.status));const liveStatus=ride?.status||b.status;const battery=b.battery==null?null:Number(b.battery);const condition=["Maintenance","Out of Service"].includes(b.status)?"Service":b.status==="Charging"?"Charging":battery!=null&&battery<30?"Low battery":"Good";return {...b,liveStatus,liveDriver:ride?.driver||b.driver||"",condition};});
 const activityTitle=(h:any)=>{
  const guest=h.guest||h.bookingId||"Guest",buggy=h.buggyName||"Buggy",driver=h.driver||"Driver";
  if(h.type==="Requested")return guest+" requested a buggy";
  if(["Assigned","Auto assigned"].includes(h.type))return buggy+" assigned to "+guest;
  if(h.type==="Driver on the way")return driver+" started pickup for "+guest;
  if(h.type==="Arrived")return driver+" arrived for "+guest;
  if(h.type==="On trip")return guest+" is on trip in "+buggy;
  if(h.type==="Cancelled")return "Ride cancelled for "+guest;
  if(h.type==="Completed")return "Ride completed for "+guest;
  return buggy+" · "+String(h.type||"Update")+" · "+guest;
 };
 return <section className="page buggy-management"><header className="buggy-management-title"><div className="buggy-title-icon"><CarFront/></div><div><h1><UiText>Nirili Ride</UiText></h1><p><UiText>Nirili Travels local ride operations: live buggy rides, guest pickups, fleet availability and driver progress in one place.</UiText></p></div><div className="buggy-title-actions"><button onClick={()=>setTab("Dispatch")}><MapPin/><UiText>Dispatch board</UiText></button><button className="primary" onClick={()=>setManualBooking({guest:"",phone:"",date,pickupTime:"",location:"Nirili Villa",destination:"",quantity:1,notes:""})}><Plus/><UiText>Book buggy</UiText></button></div></header>
  <nav className="buggy-tabs" aria-label="Nirili Ride management sections">{(["Overview","Dispatch","Fleet","Maintenance","Tracking"] as Tab[]).map(x=><button key={x} className={tab===x?"active":""} onClick={()=>setTab(x)}><UiText>{x}</UiText></button>)}</nav>
  <div className="buggy-datebar"><label><UiText>Working date</UiText><DateFieldDMY value={date} onChange={setDate} ariaLabel="Nirili Ride working date"/></label><button onClick={()=>void load()} disabled={loading}><RefreshCw/><UiText>{loading?"Refreshing…":"Refresh"}</UiText></button><span><UiText>Showing </UiText>{selectedDateLabel}</span></div>
  {message&&<p className="buggy-management-message" role="status"><UiText>{message}</UiText></p>}
  {tab==="Overview"&&<>
   <div className="buggy-live-kpis">
    <article className="active"><span><CarFront/></span><div><small><UiText>Active jobs</UiText></small><strong>{activeJobs}</strong><p><UiText>Open rides and pickups</UiText></p></div></article>
    <article className="waiting"><span><CalendarDays/></span><div><small><UiText>Waiting assignment</UiText></small><strong>{waitingAssignment}</strong><p><UiText>Needs dispatch</UiText></p></div></article>
    <article className="onway"><span><MapPin/></span><div><small><UiText>Driver on the way</UiText></small><strong>{driverOnWay}</strong><p><UiText>Heading to guest</UiText></p></div></article>
    <article className="arrived"><span><UserRound/></span><div><small><UiText>Arrived</UiText></small><strong>{arrived}</strong><p><UiText>Waiting for guest</UiText></p></div></article>
    <article className="ontrip"><span><CarFront/></span><div><small><UiText>On trip</UiText></small><strong>{onTrip}</strong><p><UiText>Guests in buggy</UiText></p></div></article>
    <article className="available"><span><CheckCircle2/></span><div><small><UiText>Available buggies</UiText></small><strong>{available}</strong><p><UiText>Ready for dispatch</UiText></p></div></article>
   </div>
   <div className="buggy-live-layout">
    <section className="buggy-card buggy-live-operations">
     <header className="buggy-live-header"><div><span className="buggy-live-label"><i/><UiText>LIVE OPERATIONS</UiText></span><h2><UiText>Current buggy jobs</UiText></h2><p><UiText>Auto-refreshing guest rides and scheduled pickups.</UiText></p></div><div className="buggy-live-header-actions"><span><CalendarDays/>{selectedDateLabel}</span><button onClick={()=>setTab("Dispatch")}><UiText>Open dispatch</UiText></button></div></header>
     {!dispatches.length?<div className="buggy-live-empty"><CheckCircle2/><strong><UiText>No buggy jobs for this date</UiText></strong><span><UiText>New guest requests and scheduled pickups will appear here automatically.</UiText></span></div>:<div className="buggy-live-table"><table><thead><tr><th><UiText>Time</UiText></th><th><UiText>Guest</UiText></th><th><UiText>Route / service</UiText></th><th><UiText>Room</UiText></th><th><UiText>Driver</UiText></th><th><UiText>Buggy</UiText></th><th><UiText>Status</UiText></th><th><UiText>Next action</UiText></th></tr></thead><tbody>{dispatches.slice(0,8).map(row=><tr key={row.id} className={activeStatuses(row.status)?"live-row":"finished-row"}><td><b>{row.pickupTime||"Arrange"}</b></td><td><b>{row.guest}</b><small>{row.phone||row.id}</small></td><td><b>{row.location} → {row.destination}</b><small>{row.service}</small></td><td>{row.room||"—"}</td><td>{row.driver||"—"}</td><td><b>{row.buggyId?fleet.find(b=>b.id===row.buggyId)?.name||row.buggyId:"—"}</b></td><td><span className={"buggy-dispatch-status "+String(row.status).toLowerCase().replace(/\s+/g,"-")}><UiText>{row.status}</UiText></span></td><td><span className="buggy-next-action"><UiText>{nextAction(row)}</UiText></span></td></tr>)}</tbody></table>{dispatches.length>8&&<button className="buggy-view-all" onClick={()=>setTab("Dispatch")}><UiText>View all {dispatches.length} operations →</UiText></button>}</div>}
    </section>
    <aside className="buggy-live-side">
     <section className="buggy-card buggy-live-fleet"><header><div><small><UiText>FLEET STATUS</UiText></small><h2><UiText>Buggy availability</UiText></h2><p><UiText>Live vehicle status and condition.</UiText></p></div><button onClick={()=>setTab("Fleet")}><UiText>Manage</UiText></button></header>{!liveFleet.length?<div className="buggy-empty"><CarFront/><strong><UiText>No buggies added</UiText></strong></div>:<div className="buggy-live-fleet-table"><div className="head"><span><UiText>Buggy</UiText></span><span><UiText>Status</UiText></span><span><UiText>Driver</UiText></span><span><UiText>Battery</UiText></span></div>{liveFleet.map(b=><button key={b.id} onClick={()=>{setBuggyForm({...b,battery:b.battery??""});setTab("Fleet")}}><span className="vehicle"><i className={"buggy-dot "+String(b.status).toLowerCase().replace(/\s+/g,"-")}/><b>{b.name}</b><small>{b.condition}</small></span><span><em className={"buggy-fleet-live-status "+String(b.liveStatus).toLowerCase().replace(/\s+/g,"-")}><UiText>{b.liveStatus}</UiText></em></span><span>{b.liveDriver||"—"}</span><span>{b.battery==null?"—":b.battery+"%"}</span></button>)}</div>}</section>
     <section className="buggy-card buggy-live-activity"><header><div><small><UiText>RECENT ACTIVITY</UiText></small><h2><UiText>What just happened</UiText></h2><p><UiText>Latest driver and dispatch updates.</UiText></p></div><button onClick={()=>setTab("Tracking")}><UiText>View all</UiText></button></header>{!history.length?<div className="buggy-activity-empty"><ShieldAlert/><UiText>No activity recorded yet.</UiText></div>:<div className="buggy-activity-list">{history.slice(0,6).map(h=><article key={h.id}><i className={"activity-dot "+String(h.type||"").toLowerCase().replace(/\s+/g,"-")}/><time>{new Date(h.at).toLocaleTimeString("en-GB",{timeZone:"Indian/Maldives",hour:"2-digit",minute:"2-digit",hour12:false})}</time><div><b>{activityTitle(h)}</b><small>{h.driver?"Driver "+h.driver+" · ":""}{h.buggyName||h.bookingId}</small></div></article>)}</div>}</section>
    </aside>
   </div>
   <div className="buggy-overview-bottom">
    <section className="buggy-card buggy-guest-pricing compact"><header><div><small><UiText>IN-HOUSE GUEST RIDES</UiText></small><h2><UiText>Guest ride pricing</UiText></h2><p><UiText>Flat fare posted automatically to the guest's main room bill.</UiText></p></div><CarFront/></header><div className="buggy-price-editor"><label><UiText>Flat fare per ride (USD)</UiText><span><b>$</b><input type="number" min={0} max={1000} step="0.01" disabled={!canChangePricing} value={guestRideFare} onChange={e=>{fareDirty.current=true;setGuestRideFare(e.target.value)}}/></span></label><div><strong>{Number(guestRideFare)>0?"$"+Number(guestRideFare).toFixed(2):"$0.00"}</strong><small><UiText>{Number(guestRideFare)>0?"Added to new guest rides.":"No charge configured."}</UiText></small></div><button className="primary" disabled={!canChangePricing||busy.startsWith("save-settings")||!Number.isFinite(Number(guestRideFare))||Number(guestRideFare)<0} onClick={()=>void action({action:"save-settings",guestRideFareCents:Math.round(Number(guestRideFare)*100)},"Guest ride fare saved.")}><UiText>{!canChangePricing?"Admin only":busy.startsWith("save-settings")?"Saving…":"Save fare"}</UiText></button></div></section>
    <section className="buggy-book-cta"><div><span><Plus/></span><div><h3><UiText>Need to arrange a pickup?</UiText></h3><p><UiText>Reception and Admin can create a manual buggy booking here.</UiText></p></div></div><button className="primary" onClick={()=>setManualBooking({guest:"",phone:"",date,pickupTime:"",location:"Nirili Villa",destination:"",quantity:1,notes:""})}><Plus/><UiText>Book buggy</UiText></button></section>
   </div>
  </>}
  {tab==="Dispatch"&&<section className="buggy-card buggy-dispatch-full"><header><div><small>{selectedDateLabel}</small><h2><UiText>Guest pickup dispatch</UiText></h2><p><UiText>Assign a buggy and driver to each scheduled pickup.</UiText></p></div><span>{dispatches.length} <UiText>pickups</UiText></span></header><DispatchTable rows={dispatches} fleet={fleet} assign={(id,buggyId,driver)=>action({action:"assign",id,buggyId,driver},"Buggy assigned.")}/></section>}
  {tab==="Fleet"&&<section className="buggy-fleet-section"><header className="buggy-section-heading"><div><h2><UiText>Fleet</UiText></h2><p><UiText>Manage availability, capacity, drivers and tracking identifiers.</UiText></p></div><button className="primary" onClick={()=>setBuggyForm({...emptyBuggy})}><Plus/><UiText>Add buggy</UiText></button></header><div className="buggy-fleet-grid">{fleet.map(b=><article key={b.id}><header><span className={"buggy-dot "+b.status.toLowerCase().replace(/\s+/g,"-")}/><div><h3>{b.name}</h3><small><UiText>{b.status}</UiText></small></div>{b.ownerId?null:<button onClick={()=>setBuggyForm({...b,battery:b.battery??""})}><Settings2/></button>}</header>{b.ownerId&&<p className="buggy-owner-note">Owned by {b.ownerName||"an independent owner"} · managed in the operator portal</p>}<div className="buggy-fleet-details"><p><span><UiText>Capacity</UiText></span><b>{b.capacity} <UiText>guests</UiText></b></p><p><span><UiText>Driver</UiText></span><b>{b.driver||"Not assigned"}</b></p><p><span><UiText>Battery</UiText></span><b>{b.battery==null?"—":b.battery+"%"}</b></p><p><span><UiText>GPS tracker</UiText></span><b>{b.trackerId?"Configured":"Not connected"}</b></p>{b.maintenanceDue&&<p><span><UiText>Service due</UiText></span><b>{b.maintenanceDue.split("-").reverse().join("-")}</b></p>}</div>{b.ownerId?null:<select value={b.status} onChange={e=>void action({action:"set-status",id:b.id,status:e.target.value},"Buggy status updated.")}>{statuses.map(s=><option key={s}>{s}</option>)}</select>}</article>)}{!fleet.length&&<div className="buggy-empty large"><CarFront/><strong><UiText>No buggy fleet configured</UiText></strong><span><UiText>Add Buggy 1, Buggy 2 and your other vehicles here.</UiText></span></div>}</div></section>}
  {tab==="Maintenance"&&<section className="buggy-card"><header><div><small><UiText>VEHICLE CARE</UiText></small><h2><UiText>Maintenance history</UiText></h2><p><UiText>Record services, repairs, tyres, batteries and inspections.</UiText></p></div><button className="primary" disabled={!fleet.length} onClick={()=>setMaintenanceForm({buggyId:fleet[0]?.id||"",date,islandDate:date,kind:"Service",notes:"",cost:"",setMaintenance:false})}><Plus/><UiText>Add record</UiText></button></header><div className="buggy-maintenance-list">{maintenance.length?maintenance.map(m=><article key={m.id}><Wrench/><div><b>{m.buggyName} · <UiText>{m.kind}</UiText></b><span>{String(m.date||"").split("-").reverse().join("-")}{m.notes?" · "+m.notes:""}</span></div><strong>{Number(m.cost)>0?"$"+Number(m.cost).toFixed(2):"—"}</strong></article>):<div className="buggy-empty"><Wrench/><strong><UiText>No maintenance records</UiText></strong><span><UiText>Service and repair records will appear here.</UiText></span></div>}</div></section>}
  {tab==="Tracking"&&<div className="buggy-tracking-grid"><section className="buggy-card"><header><div><small><UiText>GPS READINESS</UiText></small><h2><UiText>Tracking setup</UiText></h2></div><span>{trackerCount}/{fleet.length}</span></header><p className="buggy-tracking-note"><MapPin/><span><UiText>Tracker IDs can be saved now. Live map positions will activate when a GPS provider or driver-phone location feed is connected.</UiText></span></p><div className="buggy-tracker-list">{fleet.map(b=><article key={b.id}><div><b>{b.name}</b><small>{b.trackerProvider||"No provider"} · {b.trackerId||"No tracker ID"}</small></div><span className={b.trackerId?"ready":"missing"}>{b.trackerId?<UiText>Ready</UiText>:<UiText>Not configured</UiText>}</span><button onClick={()=>setBuggyForm({...b,battery:b.battery??""})}><UiText>Configure</UiText></button></article>)}</div></section><section className="buggy-card"><header><div><small><UiText>ACTIVITY</UiText></small><h2><UiText>Assignment history</UiText></h2></div></header><div className="buggy-history">{history.length?history.slice(0,15).map(h=><p key={h.id}><CarFront/><span><b>{h.buggyName}</b> <UiText>{h.type}</UiText> · {h.guest||h.bookingId}<small>{new Date(h.at).toLocaleString("en-GB",{timeZone:"Indian/Maldives"})}{h.driver?" · "+h.driver:""}</small></span></p>):<div className="buggy-empty"><ShieldAlert/><strong><UiText>No assignment history yet</UiText></strong></div>}</div></section></div>}
  {manualBooking&&<div className="buggy-modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&setManualBooking(null)}><form className="buggy-modal" onSubmit={createManualBooking}><header><div><small><UiText>RECEPTION / ADMIN</UiText></small><h2><UiText>Book buggy</UiText></h2><p><UiText>Create a manual guest pickup. Drivers can only operate assigned rides.</UiText></p></div><button type="button" onClick={()=>setManualBooking(null)}>×</button></header><div className="buggy-form-grid"><label><UiText>Guest name</UiText><input required maxLength={100} value={manualBooking.guest} onChange={e=>setManualBooking({...manualBooking,guest:e.target.value})}/></label><label><UiText>Phone number</UiText><input type="tel" maxLength={30} value={manualBooking.phone} onChange={e=>setManualBooking({...manualBooking,phone:e.target.value})}/></label><label><UiText>Date</UiText><DateFieldDMY required value={manualBooking.date} onChange={value=>setManualBooking({...manualBooking,date:value})} ariaLabel="Manual buggy booking date"/></label><label><UiText>Pickup time</UiText><input required type="text" inputMode="numeric" pattern="(?:[01]\\d|2[0-3]):[0-5]\\d" placeholder="HH:mm" value={manualBooking.pickupTime} onChange={e=>setManualBooking({...manualBooking,pickupTime:e.target.value})}/></label><label><UiText>Pickup point</UiText><input required maxLength={150} value={manualBooking.location} onChange={e=>setManualBooking({...manualBooking,location:e.target.value})}/></label><label><UiText>Drop-off point</UiText><input required maxLength={150} value={manualBooking.destination} onChange={e=>setManualBooking({...manualBooking,destination:e.target.value})}/></label><label><UiText>Guests</UiText><input required type="number" min={1} max={20} value={manualBooking.quantity} onChange={e=>setManualBooking({...manualBooking,quantity:Number(e.target.value)})}/></label><label className="full"><UiText>Notes</UiText><textarea rows={3} maxLength={500} value={manualBooking.notes} onChange={e=>setManualBooking({...manualBooking,notes:e.target.value})}/></label></div><footer><span/><button type="button" disabled={busy==="manual-booking"} onClick={()=>setManualBooking(null)}><UiText>Cancel</UiText></button><button className="primary" disabled={busy==="manual-booking"}><UiText>{busy==="manual-booking"?"Booking…":"Create booking"}</UiText></button></footer></form></div>}
  {buggyForm&&<div className="buggy-modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&setBuggyForm(null)}><form className="buggy-modal" onSubmit={e=>{e.preventDefault();void action({action:"save-buggy",...buggyForm},"Buggy saved.")}}><header><div><small><UiText>FLEET</UiText></small><h2><UiText>{buggyForm.id?"Edit buggy":"Add buggy"}</UiText></h2></div><button type="button" onClick={()=>setBuggyForm(null)}>×</button></header><div className="buggy-form-grid"><label><UiText>Buggy name</UiText><input required maxLength={80} placeholder="Buggy 1" value={buggyForm.name} onChange={e=>setBuggyForm({...buggyForm,name:e.target.value})}/></label><label><UiText>Capacity</UiText><input type="number" min={1} max={20} value={buggyForm.capacity} onChange={e=>setBuggyForm({...buggyForm,capacity:Number(e.target.value)})}/></label><label><UiText>Status</UiText><select value={buggyForm.status} onChange={e=>setBuggyForm({...buggyForm,status:e.target.value})}>{statuses.map(s=><option key={s}>{s}</option>)}</select></label><label><UiText>Battery %</UiText><input type="number" min={0} max={100} value={buggyForm.battery} onChange={e=>setBuggyForm({...buggyForm,battery:e.target.value})}/></label><label><UiText>Default driver</UiText><input maxLength={100} value={buggyForm.driver} onChange={e=>setBuggyForm({...buggyForm,driver:e.target.value})}/></label><label><UiText>Driver phone</UiText><input type="tel" maxLength={30} value={buggyForm.driverPhone} onChange={e=>setBuggyForm({...buggyForm,driverPhone:e.target.value})}/></label><label><UiText>GPS provider</UiText><input maxLength={80} placeholder="Traccar / Teltonika / Phone" value={buggyForm.trackerProvider} onChange={e=>setBuggyForm({...buggyForm,trackerProvider:e.target.value})}/></label><label><UiText>Tracker ID</UiText><input maxLength={120} value={buggyForm.trackerId} onChange={e=>setBuggyForm({...buggyForm,trackerId:e.target.value})}/></label><label><UiText>Maintenance due</UiText><input type="date" value={buggyForm.maintenanceDue} onChange={e=>setBuggyForm({...buggyForm,maintenanceDue:e.target.value})}/></label><label className="full"><UiText>Notes</UiText><textarea rows={3} maxLength={500} value={buggyForm.notes} onChange={e=>setBuggyForm({...buggyForm,notes:e.target.value})}/></label></div><footer>{buggyForm.id&&<button type="button" className="danger" onClick={()=>{if(confirm("Delete "+buggyForm.name+" from the buggy fleet?"))void action({action:"delete-buggy",id:buggyForm.id},"Buggy deleted.")}}><Trash2/><UiText>Delete</UiText></button>}<span/><button type="button" onClick={()=>setBuggyForm(null)}><UiText>Cancel</UiText></button><button className="primary" disabled={busy.startsWith("save-buggy")}><UiText>{busy.startsWith("save-buggy")?"Saving…":"Save buggy"}</UiText></button></footer></form></div>}
  {maintenanceForm&&<div className="buggy-modal-backdrop"><form className="buggy-modal small" onSubmit={e=>{e.preventDefault();void action({action:"maintenance",...maintenanceForm},"Maintenance record added.")}}><header><div><small><UiText>MAINTENANCE</UiText></small><h2><UiText>Add record</UiText></h2></div><button type="button" onClick={()=>setMaintenanceForm(null)}>×</button></header><div className="buggy-form-grid"><label><UiText>Buggy</UiText><select value={maintenanceForm.buggyId} onChange={e=>setMaintenanceForm({...maintenanceForm,buggyId:e.target.value})}>{fleet.map(b=><option value={b.id} key={b.id}>{b.name}</option>)}</select></label><label><UiText>Date</UiText><input required type="date" value={maintenanceForm.date} onChange={e=>setMaintenanceForm({...maintenanceForm,date:e.target.value})}/></label><label><UiText>Type</UiText><select value={maintenanceForm.kind} onChange={e=>setMaintenanceForm({...maintenanceForm,kind:e.target.value})}><UiOption>Service</UiOption><UiOption>Repair</UiOption><UiOption>Battery</UiOption><UiOption>Tyres</UiOption><UiOption>Brakes</UiOption><UiOption>Inspection</UiOption><UiOption>Cleaning</UiOption><UiOption>Other</UiOption></select></label><label><UiText>Cost USD</UiText><input type="number" min={0} step="0.01" value={maintenanceForm.cost} onChange={e=>setMaintenanceForm({...maintenanceForm,cost:e.target.value})}/></label><label className="full"><UiText>Notes</UiText><textarea rows={3} maxLength={500} value={maintenanceForm.notes} onChange={e=>setMaintenanceForm({...maintenanceForm,notes:e.target.value})}/></label><label className="full checkbox"><input type="checkbox" checked={maintenanceForm.setMaintenance} onChange={e=>setMaintenanceForm({...maintenanceForm,setMaintenance:e.target.checked})}/><UiText>Mark this buggy as Maintenance</UiText></label></div><footer><span/><button type="button" onClick={()=>setMaintenanceForm(null)}><UiText>Cancel</UiText></button><button className="primary"><UiText>Add record</UiText></button></footer></form></div>}
 </section>;
}

function DispatchTable({rows,fleet,assign}:{rows:any[];fleet:any[];assign:(id:string,buggyId:string,driver:string)=>void}){
 const [drivers,setDrivers]=useState<Record<string,string>>({});
 if(!rows.length)return <div className="buggy-empty"><CalendarDays/><strong><UiText>No buggy pickups for this date</UiText></strong><span><UiText>Manual bookings and confirmed guest transfers will appear here.</UiText></span></div>;
 return <div className="buggy-dispatch-table"><table><thead><tr><th><UiText>Time</UiText></th><th><UiText>Guest</UiText></th><th><UiText>Route / service</UiText></th><th><UiText>Guests</UiText></th><th><UiText>Status</UiText></th><th><UiText>Buggy</UiText></th><th><UiText>Driver</UiText></th><th><UiText>Action</UiText></th></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td><b>{row.pickupTime||"Arrange"}</b></td><td><b>{row.guest}</b><small>{row.room?"Room "+row.room:""}{row.phone?(row.room?" · ":"")+row.phone:""}</small></td><td><b>{row.location} → {row.destination}</b><small>{row.service}</small></td><td>{row.quantity}</td><td><span className={"buggy-dispatch-status "+String(row.status).toLowerCase().replace(/\s+/g,"-")}><UiText>{row.status}</UiText></span></td><td><select defaultValue={row.buggyId||""} id={"buggy-"+row.id}><option value=""><UiText>Choose</UiText></option>{fleet.filter(b=>(!b.ownerId&&!["Maintenance","Out of Service"].includes(b.status))||b.id===row.buggyId).map(b=><option key={b.id} value={b.id} disabled={!!b.ownerId}>{b.name} · {b.ownerId?(b.ownerName||"Owner"):b.status}</option>)}</select></td><td><input aria-label={"Driver for "+row.guest} placeholder="Driver" defaultValue={row.driver||""} onChange={e=>setDrivers({...drivers,[row.id]:e.target.value})}/></td><td><button disabled={!fleet.length} onClick={()=>{const select=document.getElementById("buggy-"+row.id) as HTMLSelectElement|null;if(select?.value)assign(row.id,select.value,drivers[row.id]??row.driver??"")}}><UiText>Assign</UiText></button></td></tr>)}</tbody></table></div>;
}
