'use client';
import {useEffect,useRef,useState} from 'react';
import {X} from 'lucide-react';
import {islandToday,plans} from '../lib/guest-catalog';

export default function DirectBookingForm({close,onSaved,booking}:{close:()=>void;onSaved:(stay:any)=>void;booking?:any}){
 const [data,setData]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const [guest,setGuest]=useState(booking?.guest||''),[source,setSource]=useState(booking?.source||'Direct'),[checkIn,setCheckIn]=useState(booking?.checkIn||islandToday()),[checkOut,setCheckOut]=useState(()=>booking?.checkOut||new Date(Date.parse(islandToday())+86400000).toISOString().slice(0,10)),[pax,setPax]=useState(booking?.pax||1),[room,setRoom]=useState(booking?.room||''),[meal,setMeal]=useState(booking?.meal||plans[0]),[rate,setRate]=useState(booking?String((booking.rateCents??Math.round(booking.base/((Date.parse(booking.checkOut)-Date.parse(booking.checkIn))/86400000)))/100):'60');
 const token=useRef(''),saving=useRef(false);
 async function refresh(){const r=await fetch('/api/stays',{cache:'no-store'});const d=await r.json();if(!r.ok)throw Error(d.error||'Could not load room availability.');setData(d);return d;}
 useEffect(()=>{token.current=crypto.randomUUID();refresh().catch(e=>setError(e.message));},[]);
 const available=(data?.rooms||[]).filter((r:any)=>r.status!=='Maintenance'&&pax<=r.capacity&&!data.stays.some((s:any)=>s.id!==booking?.id&&s.room===r.number&&s.status!=='Checked Out'&&s.checkIn<checkOut&&s.checkOut>checkIn));
 const nights=Math.max(0,(Date.parse(checkOut)-Date.parse(checkIn))/86400000)||0;
 async function submit(e:React.FormEvent){e.preventDefault();if(saving.current||!data)return;saving.current=true;setBusy(true);setError('');try{const r=await fetch('/api/stays',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:booking?'editbooking':'create',id:booking?.id,requestId:token.current,revision:booking?booking.editRevision:data.revision,guest,source,checkIn,checkOut,pax,room,meal,rateCents:Math.round(Number(rate)*100)})});const d=await r.json();if(!r.ok){if(r.status===409)await refresh();throw Error(d.error||'Could not save booking.');}window.dispatchEvent(new Event('services-updated'));onSaved(d.booking);}catch(e){setError((e as Error).message);}finally{saving.current=false;setBusy(false);}}
 return <div className="backdrop" style={{zIndex:10001}}><form className="modal" role="dialog" aria-modal="true" aria-labelledby="direct-booking-title" onSubmit={submit}><header><div><small>{booking?booking.id:"NEW RESERVATION"}</small><h2 id="direct-booking-title">{booking?"Edit booking":"Create booking"}</h2></div><button type="button" disabled={busy} onClick={close} aria-label="Close"><X/></button></header><div className="form"><label>Guest name<input autoFocus required maxLength={100} placeholder="Full name" value={guest} onChange={e=>setGuest(e.target.value)}/></label><label>Booking source<select value={source} onChange={e=>setSource(e.target.value)}>{['Direct','Walk-in','Booking.com','Agoda','Travel agent','Guest portal'].map(x=><option key={x}>{x}</option>)}</select></label><label>Check-in<input required type="date" value={checkIn} onChange={e=>{setCheckIn(e.target.value);setRoom('');}}/></label><label>Check-out<input required type="date" min={checkIn?new Date(Date.parse(checkIn)+86400000).toISOString().slice(0,10):undefined} value={checkOut} onChange={e=>{setCheckOut(e.target.value);setRoom('');}}/></label><label>Adults<select value={pax} onChange={e=>{setPax(Number(e.target.value));setRoom('');}}>{[1,2,3].map(x=><option key={x}>{x}</option>)}</select></label><label>Room<select required disabled={!data||busy} value={room} onChange={e=>setRoom(e.target.value)}><option value="">{data?'Choose an available room':'Loading rooms…'}</option>{available.map((r:any)=><option key={r.number} value={r.number}>Room {r.number}</option>)}</select></label>{data&&!available.length&&<p>No rooms available for these dates and guest count.</p>}<label>Meal plan<select value={meal} onChange={e=>setMeal(e.target.value)}>{plans.map(x=><option key={x}>{x}</option>)}</select></label><label>Nightly rate (USD)<input required type="number" min="0" max="10000" step="0.01" value={rate} onChange={e=>setRate(e.target.value)}/></label><p>{nights} nights · Accommodation total: <b>${(nights*Math.round(Number(rate)*100)/100).toFixed(2)}</b></p><p>{booking?"Changes update this reservation and its room assignment. Existing payments are retained.":"Saved as Confirmed in the selected room. Check in when the guest arrives."}</p>{error&&<p role="alert">{error}</p>}{!data&&error&&<button type="button" onClick={()=>refresh().catch(e=>setError(e.message))}>Retry loading rooms</button>}</div><footer><button type="button" disabled={busy} onClick={close}>Cancel</button><button className="primary" disabled={busy||!data||!room||nights<1}>{busy?'Saving booking…':booking?'Save changes':'Confirm Booking'}</button></footer></form></div>;
}
