'use client';
import {useEffect,useState} from 'react';
import {Clock,Users,ShipWheel,X,CalendarDays,CheckCircle2} from 'lucide-react';
import './excursion-catalog.css';

function maldivesToday(){const p=new Intl.DateTimeFormat('en-US',{timeZone:'Indian/Maldives',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date());const g=(t:string)=>p.find(x=>x.type===t)?.value||'';return `${g('year')}-${g('month')}-${g('day')}`;}
const shift=(date:string,days:number)=>new Date(Date.parse(date+'T00:00:00Z')+days*86400000).toISOString().slice(0,10);
const usd=(cents:number)=>'$'+((Number(cents)||0)/100).toFixed(2);
const friendlyDate=(date:string)=>new Intl.DateTimeFormat('en-US',{timeZone:'Indian/Maldives',weekday:'short',month:'short',day:'numeric',year:'numeric'}).format(new Date(date+'T00:00:00+05:00'));

export default function ExcursionCatalog({canBook=true}:{items:any[];onBook?:(item:any)=>void;canBook?:boolean}){
 const [date,setDate]=useState(maldivesToday()),[data,setData]=useState<any>(null),[loading,setLoading]=useState(false),[message,setMessage]=useState(''),[booking,setBooking]=useState<any>(null),[saving,setSaving]=useState(false);
 async function load(selected=date,silent=false){if(!silent){setLoading(true);setMessage('');}try{const r=await fetch('/api/guest-excursion-schedules?date='+encodeURIComponent(selected),{cache:'no-store'}),d=await r.json();if(!r.ok)throw Error(d.error||'Could not load excursions');setData(d);}catch(e){if(!silent)setMessage((e as Error).message);}finally{if(!silent)setLoading(false);}}
 useEffect(()=>{load(date)},[date]);
 useEffect(()=>{const onRefresh=()=>void load(date,true);window.addEventListener('nirili:auto-refresh',onRefresh);return()=>window.removeEventListener('nirili:auto-refresh',onRefresh)},[date]);
 function openBooking(schedule:any){const stay=data?.stays?.[0];setBooking({scheduleId:schedule.id,date:schedule.date,name:schedule.name,time:schedule.time,stayId:stay?.id||'',quantity:1,notes:'',token:crypto.randomUUID(),capacity:schedule.capacity,confirmedPax:schedule.confirmedPax,remainingSeats:schedule.remainingSeats,priceCents:schedule.priceCents||0});setMessage('');}
 async function submit(e:React.FormEvent){e.preventDefault();if(!booking||saving)return;setSaving(true);setMessage('');try{const r=await fetch('/api/guest-excursion-schedules',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(booking)}),d=await r.json();if(!r.ok)throw Error(d.error||'Could not book seats');setBooking(null);setMessage(d.booking?.requiresApproval?'The boat is full for this request. Your extra-seat request was sent to Admin for review.':'Your excursion seats are confirmed and the charge was added to your room bill.');await load(date);window.dispatchEvent(new Event('services-updated'));}catch(e){setMessage((e as Error).message);}finally{setSaving(false);}}
 const schedules=data?.schedules||[],stays=data?.stays||[],myBookings=data?.myBookings||[];
 return <section className="guest-excursion-schedule" aria-label="Scheduled excursions">
  <header className="guest-excursion-hero"><small>NIRILI TOURS · DHIFFUSHI</small><h2>Scheduled excursions</h2><p>Choose a scheduled departure and book seats instantly while capacity is available. Once the boat is full, you can still request extra seats and Admin will decide whether they can be accepted.</p></header>

  {myBookings.length>0&&<section className="guest-booked-excursions"><div className="guest-booked-heading"><div><small>MY EXCURSIONS</small><h3>Booked excursions</h3></div><CheckCircle2 size={24}/></div><div className="guest-booked-grid">{myBookings.map((b:any)=><article key={b.id}><div className="guest-booked-date"><CalendarDays size={17}/><span>{friendlyDate(b.date)}</span><strong>{b.time}</strong></div><h4>{b.name}</h4><div className="guest-booked-meta"><span>{b.quantity} seat{b.quantity===1?'':'s'}</span><span>Room {b.room}</span><span>{b.status}</span>{b.cents>0&&<span>{usd(b.cents)}</span>}</div></article>)}</div></section>}

  <div className="guest-excursion-controls"><div className="guest-excursion-day-label"><small>Showing excursions for</small><strong>{friendlyDate(date)}</strong></div><div className="guest-excursion-datebar"><button type="button" onClick={()=>setDate(shift(date,-1))}>← Previous</button><button type="button" onClick={()=>setDate(shift(date,1))}>Next →</button></div></div>
  {message&&<p className="guest-excursion-message" role="status">{message}</p>}
  {!canBook&&<p className="guest-excursion-note">Excursion bookings are available after check-in.</p>}
  {loading?<div className="guest-excursion-empty">Loading scheduled excursions…</div>:!schedules.length?<div className="guest-excursion-empty"><strong>No excursions scheduled for this date.</strong><span>Please choose another day.</span></div>:<div className="guest-excursion-list">{schedules.map((s:any)=>{const own=s.ownBooking,full=s.isFull,closed=s.status!=='Open',pending=own?.status==='Pending';return <article key={s.id} className={(full?'is-full ':'')+(closed?'is-closed':'')}>
   <div className="guest-excursion-time"><Clock size={18}/><strong>{s.time}</strong></div>
   <div className="guest-excursion-main"><div className="guest-excursion-title"><h3>{s.name}</h3><span className={closed?'closed':full?'full':'open'}>{closed?'Closed':full?'At capacity':'Open'}</span>{s.sharedBoat&&<span className="shared">Same boat</span>}</div><div className="guest-excursion-meta"><span><Users size={16}/>{s.confirmedPax} / {s.capacity} confirmed</span>{!full&&<span>{s.remainingSeats} seat{s.remainingSeats===1?'':'s'} available</span>}{s.priceCents>0&&<span>{usd(s.priceCents)} / guest</span>}{full&&<span className="capacity-note">Extra-seat requests accepted</span>}{s.pendingPax>0&&<span>{s.pendingPax} pax awaiting Admin</span>}</div>{s.notes&&<p>{s.notes}</p>}{own&&<div className={'guest-own-request '+String(own.status).toLowerCase().replace(/\s+/g,'-')}>Your latest booking: {own.quantity} seat{own.quantity===1?'':'s'} · {own.status}</div>}</div>
   <div className="guest-excursion-action"><button type="button" disabled={!canBook||closed||!stays.length||pending} onClick={()=>openBooking(s)}>{pending?'Request pending':full?'Request seats':'Book seats'}</button></div>
  </article>})}</div>}
  {booking&&<div className="guest-excursion-overlay"><form className="guest-excursion-dialog" onSubmit={submit}><header><div><small>{booking.confirmedPax+booking.quantity>booking.capacity?'EXTRA-SEAT REQUEST':'BOOK EXCURSION'}</small><h3>{booking.name}</h3><p>{friendlyDate(booking.date)} · {booking.time}</p></div><button type="button" aria-label="Close" onClick={()=>setBooking(null)}><X/></button></header>{booking.confirmedPax+booking.quantity>booking.capacity?<div className="guest-full-warning"><strong>Not enough listed seats for this request</strong><p>You can still send the request. Admin will review it and decide whether another arrangement or extra capacity is possible.</p></div>:<div className="guest-excursion-note"><strong>Instant confirmation</strong><p>These seats fit within the current boat capacity and will be confirmed immediately.</p></div>}<label>Room<select required value={booking.stayId} onChange={e=>setBooking({...booking,stayId:e.target.value})}><option value="">Choose room</option>{stays.map((s:any)=><option key={s.id} value={s.id}>Room {s.room} · {s.guest}</option>)}</select></label><label>Number of seats<input required type="number" min={1} max={20} value={booking.quantity} onChange={e=>setBooking({...booking,quantity:Number(e.target.value)})}/></label>{booking.priceCents>0&&<div className="guest-excursion-total"><span>Excursion charge</span><strong>{usd(booking.priceCents*booking.quantity)}</strong><small>{usd(booking.priceCents)} × {booking.quantity} guest{booking.quantity===1?'':'s'}</small></div>}<label>Notes<textarea rows={3} maxLength={1000} placeholder="Any special request or information for the team" value={booking.notes} onChange={e=>setBooking({...booking,notes:e.target.value})}/></label><p className="guest-excursion-dialog-note"><ShipWheel size={17}/> {booking.confirmedPax+booking.quantity>booking.capacity?'This request needs Admin approval because it exceeds the listed boat capacity.':'Your seats will be booked immediately and added to your room bill.'}</p><footer><button type="button" onClick={()=>setBooking(null)}>Cancel</button><button type="submit" disabled={saving}>{saving?'Saving…':booking.confirmedPax+booking.quantity>booking.capacity?'Send seat request':'Confirm booking'}</button></footer></form></div>}
 </section>;
}
