'use client';
import './excursion-scheduler.css';
import ExcursionTime from './excursion-time';
import {useState} from 'react';
import {excursionWhatsApp} from '../lib/excursion-schedule';
import {excursionStage} from '../lib/excursion-workflow';
import {islandToday} from '../lib/guest-catalog';
const usd=(n:number)=>'$'+(n/100).toFixed(2);
export default function ExcursionScheduler({data,mutate}:{data:any;mutate:(b:any)=>Promise<any>}){
 const [view,setView]=useState('All'),[edit,setEdit]=useState<any>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const orders=(data?.orders||[]).filter((o:any)=>o.kind==='excursion'),resources=data?.resources||{vessels:[],crew:[]},stays=(data?.stays||[]).filter((s:any)=>s.status==='In House');
 const views=['All','Awaiting scheduling','Scheduled','Departed','Completed','Cancelled'];
 const visible=orders.filter((o:any)=>view==='All'||excursionStage(o)===view).sort((a:any,b:any)=>{const rank=(o:any)=>['Completed','Cancelled'].includes(excursionStage(o))?2:excursionStage(o)==='Awaiting scheduling'?0:1;return rank(a)-rank(b)||((a.schedule?.date||a.date||'9999')+' '+(a.schedule?.time||'')).localeCompare((b.schedule?.date||b.date||'9999')+' '+(b.schedule?.time||''))||a.id.localeCompare(b.id)});
 async function act(body:any,success:string){setBusy(true);setMessage('');try{await mutate(body);setMessage(success);return true;}catch(e){setMessage((e as Error).message);return false;}finally{setBusy(false);}}
 function schedule(o:any){setMessage('');setEdit({action:'schedule-excursion',id:o.id,date:o.schedule?.date||o.date||islandToday(),time:o.schedule?.time||'',vesselId:o.schedule?.vesselId||resources.vessels.find((v:any)=>v.name.toLowerCase()===o.schedule?.vessel?.toLowerCase())?.id||'',crewIds:o.schedule?.crewIds||o.schedule?.crew?.map((n:string)=>resources.crew.find((c:any)=>c.name.toLowerCase()===n.toLowerCase())?.id||'')||[''],phone:o.schedule?.phone||o.phone||data.stays.find((s:any)=>s.id===o.stayId)?.whatsapp||''});}
 const used=(type:'vessels'|'crew',id:string)=>{const resource=resources[type].find((r:any)=>r.id===id);return resource&&orders.some((o:any)=>o.id!==edit?.id&&o.status!=='Cancelled'&&o.schedule?.date===edit?.date&&o.schedule?.time===edit?.time&&(type==='vessels'?o.schedule.vessel.toLowerCase()===resource.name.toLowerCase():o.schedule.crew.some((n:string)=>n.toLowerCase()===resource.name.toLowerCase())));};
 const chosen=(data?.catalog||[]).find((i:any)=>i.id===edit?.itemId);
 return <section className="booking-review excursion-scheduler"><h2>Excursion schedule &amp; bookings</h2><p>Schedule trips, assign your team and track payments. All times are Maldives local time.</p>
 {data?.canSchedule&&<div className="excursion-actions"><button className="excursion-schedule-button" onClick={()=>{setMessage('');setEdit({action:'excursion-create',token:crypto.randomUUID(),stayId:'',guest:'',phone:'',hotel:'',itemId:'',quantity:2,date:'',notes:''})}}>New excursion booking</button><button onClick={()=>{setMessage('');setEdit({action:'excursion-resource',resourceType:'vessels',name:''})}}>Vessels &amp; crew</button></div>}
 <nav className="excursion-view-tabs" aria-label="Excursion views">{views.map(v=><button type="button" key={v} aria-pressed={view===v} onClick={()=>setView(v)}>{v} ({orders.filter((o:any)=>v==='All'||excursionStage(o)===v).length})</button>)}</nav><p role="status">{message}</p>{!visible.length&&<p>No bookings in this view.</p>}
 {visible.map((o:any)=>{const stage=excursionStage(o),closed=['Completed','Cancelled'].includes(stage);return <article key={o.id}><div><b>{o.name} · {o.quantity} guests · {usd(o.cents)}</b><p>{o.guest} · {o.source==='Walk-in'?o.hotel:'Room '+(data.stays.find((s:any)=>s.id===o.stayId)?.room||o.room||'')} · {o.id}</p><p><strong>{stage}</strong> · {o.paymentStatus}</p>{o.date&&!o.schedule&&<p>Requested date: {o.date}</p>}{o.schedule&&<p>{o.schedule.date} at {o.schedule.time} (Maldives time)<br/>Vessel: {o.schedule.vessel}<br/>Crew: {o.schedule.crew.join(', ')}</p>}{o.notes&&<p>{o.notes}</p>}</div>
 {data.canSchedule&&<div className="excursion-actions">{!closed&&<>
 {stage!=='Departed'&&<button disabled={busy} className="excursion-schedule-button" onClick={()=>schedule(o)}>{o.schedule?'Edit schedule':'Schedule excursion'}</button>}
 {stage==='Scheduled'&&<button disabled={busy} onClick={()=>act({action:'excursion-status',id:o.id,status:'Departed'},'Trip marked as departed.')}>Mark departed</button>}
 {stage==='Departed'&&<button className="excursion-complete-button" title={o.paymentStatus!=='Paid'?'Receive full payment before completing':'Complete excursion'} disabled={busy||o.paymentStatus!=='Paid'} onClick={()=>act({action:'excursion-status',id:o.id,status:'Completed'},'Excursion completed.')}>Complete</button>}
 {stage!=='Departed'&&<button className="excursion-cancel-button" disabled={busy} onClick={()=>{if(confirm('Cancel this excursion booking?'))act({action:'excursion-status',id:o.id,status:'Cancelled'},'Booking cancelled.')}}>Cancel booking</button>}
 </>}
 {stage!=='Cancelled'&&o.paymentStatus!=='Paid'&&(o.stayId?<a className="excursion-room-payment" href={'/?room='+encodeURIComponent(data.stays.find((s:any)=>s.id===o.stayId)?.room||o.room||'')}>Receive payment in room bill</a>:<button disabled={busy} onClick={()=>{setMessage('');setEdit({action:'excursion-payment',id:o.id,method:'Cash',reference:'',amount:o.cents})}}>Receive payment · {usd(o.cents)}</button>)}
 {stage==='Departed'&&o.paymentStatus!=='Paid'&&<small>Full payment is required to complete this trip.</small>}
 {o.schedule&&!closed&&<p className="excursion-whatsapp"><a href={excursionWhatsApp(o)} target="_blank" rel="noopener noreferrer">Send details on WhatsApp</a><small>Press Send in WhatsApp to notify the guest.</small></p>}
 </div>}</article>})}
 {edit&&<div className="menu-overlay"><form className="menu-dialog excursion-form" onSubmit={async e=>{e.preventDefault();const ok=await act(edit,edit.action==='excursion-resource'?'List updated.':edit.action==='excursion-payment'?'Payment recorded.':edit.action==='excursion-create'?'Excursion booking created.':'Excursion scheduled. Send the details to the guest on WhatsApp.');if(ok){if(edit.action==='excursion-resource')setEdit({...edit,name:''});else setEdit(null)}}}>
 <h2>{edit.action==='excursion-create'?'New excursion booking':edit.action==='excursion-resource'?'Vessels & crew':edit.action==='excursion-payment'?'Receive payment':'Schedule excursion'}</h2><fieldset disabled={busy}>
 {edit.action==='excursion-create'&&<>
 <label>Guest type / room<select value={edit.stayId} onChange={e=>{const s=stays.find((s:any)=>s.id===e.target.value);setEdit({...edit,stayId:e.target.value,guest:s?.guest||'',phone:s?.whatsapp||''})}}><option value="">Walk-in / external guest</option>{stays.map((s:any)=><option key={s.id} value={s.id}>Room {s.room} · {s.guest}</option>)}</select></label>
 <label>Guest name<input required maxLength={100} readOnly={!!edit.stayId} value={edit.guest} onChange={e=>setEdit({...edit,guest:e.target.value})}/></label><label>WhatsApp number<input required type="tel" placeholder="+960…" value={edit.phone} onChange={e=>setEdit({...edit,phone:e.target.value})}/></label>
 {!edit.stayId&&<label>Hotel / meeting location<input required maxLength={150} value={edit.hotel} onChange={e=>setEdit({...edit,hotel:e.target.value})}/></label>}
 <label>Excursion<select required value={edit.itemId} onChange={e=>setEdit({...edit,itemId:e.target.value})}><option value="">Choose excursion</option>{(data.catalog||[]).filter((i:any)=>i.kind==='excursion').map((i:any)=><option key={i.id} value={i.id}>{i.name} · {usd(i.cents)} / guest</option>)}</select></label>
 <label>Guests<input required type="number" min={1} max={100} value={edit.quantity} onChange={e=>setEdit({...edit,quantity:Number(e.target.value)})}/></label><label>Requested date (optional)<input type="date" min={islandToday()} value={edit.date} onChange={e=>setEdit({...edit,date:e.target.value})}/></label><label>Notes<textarea maxLength={1000} value={edit.notes} onChange={e=>setEdit({...edit,notes:e.target.value})}/></label>{chosen&&<p>Total: {usd(chosen.cents*edit.quantity)}{edit.stayId?' · Added to room bill':''}</p>}
 </>}
 {edit.action==='excursion-resource'&&<><p>Add each vessel and crew member once. Scheduling uses these lists.</p><label>List<select value={edit.resourceType} onChange={e=>setEdit({...edit,resourceType:e.target.value})}><option value="vessels">Vessels</option><option value="crew">Crew members</option></select></label><ul>{resources[edit.resourceType].map((r:any)=><li key={r.id}>{r.name}</li>)}</ul><label>Name<input required maxLength={100} value={edit.name} onChange={e=>setEdit({...edit,name:e.target.value})}/></label></>}
 {edit.action==='excursion-payment'&&<><p>Record full payment received: <strong>{usd(edit.amount)}</strong></p><label>Method<select value={edit.method} onChange={e=>setEdit({...edit,method:e.target.value})}><option>Cash</option><option>Card</option><option>Bank transfer</option></select></label><label>Receipt / reference<input maxLength={150} value={edit.reference} onChange={e=>setEdit({...edit,reference:e.target.value})}/></label><p>Save only after receiving the payment.</p></>}
 {edit.action==='schedule-excursion'&&<><label>Date<input type="date" required min={islandToday()} value={edit.date} onChange={e=>setEdit({...edit,date:e.target.value})}/></label><ExcursionTime key={edit.id} initial={edit.time} onChange={time=>setEdit((current:any)=>({...current,time}))}/><label>Vessel<select required value={edit.vesselId} onChange={e=>setEdit({...edit,vesselId:e.target.value})}><option value="">Select vessel</option>{resources.vessels.map((r:any)=><option key={r.id} value={r.id} disabled={used('vessels',r.id)}>{r.name}{used('vessels',r.id)?' — already booked':''}</option>)}</select></label>{edit.crewIds.map((id:string,i:number)=><label key={i}>Crew member {i+1}<select required value={id} onChange={e=>setEdit({...edit,crewIds:edit.crewIds.map((x:string,j:number)=>i===j?e.target.value:x)})}><option value="">Select crew member</option>{resources.crew.map((r:any)=><option key={r.id} value={r.id} disabled={used('crew',r.id)||edit.crewIds.some((x:string,j:number)=>j!==i&&x===r.id)}>{r.name}{used('crew',r.id)?' — already booked':''}</option>)}</select>{edit.crewIds.length>1&&<button type="button" onClick={()=>setEdit({...edit,crewIds:edit.crewIds.filter((_:string,j:number)=>j!==i)})}>Remove</button>}</label>)}<button type="button" disabled={edit.crewIds.length>=Math.min(20,resources.crew.length)} onClick={()=>setEdit({...edit,crewIds:[...edit.crewIds,'']})}>Add crew member</button>{(!resources.vessels.length||!resources.crew.length)&&<p>Add vessels and crew using the Vessels &amp; crew button first.</p>}<label>Guest WhatsApp number<input required type="tel" placeholder="+960…" value={edit.phone} onChange={e=>setEdit({...edit,phone:e.target.value})}/></label></>}
 <p role="alert">{message}</p><div className="excursion-actions"><button type="button" onClick={()=>setEdit(null)}>Close</button><button type="submit" className="excursion-schedule-button">{busy?'Saving…':edit.action==='excursion-resource'?'Add to list':edit.action==='excursion-payment'?'Confirm payment received':'Save'}</button></div></fieldset></form></div>}
 </section>;
}
