'use client';
import {useEffect,useState} from 'react';
import {CalendarDays,Clock,Users,ShipWheel,X} from 'lucide-react';
import './excursion-catalog.css';

function maldivesToday(){const p=new Intl.DateTimeFormat('en-US',{timeZone:'Indian/Maldives',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date());const g=(t:string)=>p.find(x=>x.type===t)?.value||'';return `${g('year')}-${g('month')}-${g('day')}`;}
const shift=(date:string,days:number)=>new Date(Date.parse(date+'T00:00:00Z')+days*86400000).toISOString().slice(0,10);

export default function ExcursionCatalog({canBook=true}:{items:any[];onBook?:(item:any)=>void;canBook?:boolean}){
 const [date,setDate]=useState(maldivesToday()),[data,setData]=useState<any>(null),[loading,setLoading]=useState(false),[message,setMessage]=useState(''),[booking,setBooking]=useState<any>(null),[saving,setSaving]=useState(false);
 async function load(selected=date){setLoading(true);setMessage('');try{const r=await fetch('/api/guest-excursion-schedules?date='+encodeURIComponent(selected),{cache:'no-store'}),d=await r.json();if(!r.ok)throw Error(d.error||'Could not load excursions');setData(d);}catch(e){setMessage((e as Error).message);}finally{setLoading(false);}}
 useEffect(()=>{load(date)},[date]);
 function openRequest(schedule:any){const stay=data?.stays?.[0];setBooking({scheduleId:schedule.id,date:schedule.date,name:schedule.name,time:schedule.time,stayId:stay?.id||'',quantity:1,notes:'',token:crypto.randomUUID(),isFull:schedule.isFull,capacity:schedule.capacity,confirmedPax:schedule.confirmedPax});setMessage('');}
 async function submit(e:React.FormEvent){e.preventDefault();if(!booking||saving)return;setSaving(true);setMessage('');try{const r=await fetch('/api/guest-excursion-schedules',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(booking)}),d=await r.json();if(!r.ok)throw Error(d.error||'Could not send request');setBooking(null);setMessage(d.request?.overCapacity?'Seat request sent. This boat is at or over the listed capacity, so Admin will review your request.':'Seat request sent to Admin for approval.');await load(date);window.dispatchEvent(new Event('services-updated'));}catch(e){setMessage((e as Error).message);}finally{setSaving(false);}}
 const schedules=data?.schedules||[],stays=data?.stays||[];
 return <section className="guest-excursion-schedule" aria-label="Scheduled excursions">
  <header className="guest-excursion-hero"><small>NIRILI TOURS · DHIFFUSHI</small><h2>Scheduled excursions</h2><p>Choose a departure and request seats. Even when the listed boat capacity is reached, you can still send a request and Admin will decide whether it can be accepted.</p></header>
  <div className="guest-excursion-datebar"><button type="button" onClick={()=>setDate(shift(date,-1))}>← Previous</button><label><CalendarDays size={18}/> <span>Date</span><input type="date" min={maldivesToday()} value={date} onChange={e=>setDate(e.target.value)}/></label><button type="button" onClick={()=>setDate(shift(date,1))}>Next →</button></div>
  {message&&<p className="guest-excursion-message" role="status">{message}</p>}
  {!canBook&&<p className="guest-excursion-note">Excursion seat requests are available after check-in.</p>}
  {loading?<div className="guest-excursion-empty">Loading scheduled excursions…</div>:!schedules.length?<div className="guest-excursion-empty"><strong>No excursions scheduled for this date.</strong><span>Please choose another day.</span></div>:<div className="guest-excursion-list">{schedules.map((s:any)=>{const own=s.ownRequest,full=s.isFull,closed=s.status!=='Open',pending=own?.status==='Pending';return <article key={s.id} className={(full?'is-full ':'')+(closed?'is-closed':'')}>
   <div className="guest-excursion-time"><Clock size={18}/><strong>{s.time}</strong></div>
   <div className="guest-excursion-main"><div className="guest-excursion-title"><h3>{s.name}</h3><span className={closed?'closed':full?'full':'open'}>{closed?'Closed':full?'At capacity':'Open'}</span>{s.sharedBoat&&<span className="shared">Same boat</span>}</div><div className="guest-excursion-meta"><span><Users size={16}/>{s.confirmedPax} / {s.capacity} confirmed</span>{!full&&<span>{s.remainingSeats} listed seat{s.remainingSeats===1?'':'s'} remaining</span>}{full&&<span className="capacity-note">Requests still accepted</span>}{s.pendingPax>0&&<span>{s.pendingPax} pax awaiting Admin</span>}</div>{s.notes&&<p>{s.notes}</p>}{own&&<div className={'guest-own-request '+String(own.status).toLowerCase().replace(/\s+/g,'-')}>Your request: {own.quantity} seat{own.quantity===1?'':'s'} · {own.status}</div>}</div>
   <div className="guest-excursion-action"><button type="button" disabled={!canBook||closed||!stays.length||pending} onClick={()=>openRequest(s)}>{pending?'Request pending':full?'Request anyway':'Request seats'}</button></div>
  </article>})}</div>}
  {booking&&<div className="guest-excursion-overlay"><form className="guest-excursion-dialog" onSubmit={submit}><header><div><small>SEAT REQUEST</small><h3>{booking.name}</h3><p>{booking.date} · {booking.time}</p></div><button type="button" aria-label="Close" onClick={()=>setBooking(null)}><X/></button></header>{booking.isFull&&<div className="guest-full-warning"><strong>Boat capacity reached</strong><p>You can still send this request. Admin will review it and decide whether another arrangement is possible.</p></div>}<label>Room<select required value={booking.stayId} onChange={e=>setBooking({...booking,stayId:e.target.value})}><option value="">Choose room</option>{stays.map((s:any)=><option key={s.id} value={s.id}>Room {s.room} · {s.guest}</option>)}</select></label><label>Number of seats<input required type="number" min={1} max={20} value={booking.quantity} onChange={e=>setBooking({...booking,quantity:Number(e.target.value)})}/></label><label>Notes<textarea rows={3} maxLength={1000} placeholder="Any special request or information for Admin" value={booking.notes} onChange={e=>setBooking({...booking,notes:e.target.value})}/></label><p className="guest-excursion-dialog-note"><ShipWheel size={17}/> This is a request, not an automatic confirmation. Admin will approve or decline it.</p><footer><button type="button" onClick={()=>setBooking(null)}>Cancel</button><button type="submit" disabled={saving}>{saving?'Sending…':'Send seat request'}</button></footer></form></div>}
 </section>;
}
