'use client';
import {useEffect,useRef,useState} from 'react';
import {MessageCircle,X,Send} from 'lucide-react';
import './guest-chat.css';
export default function GuestChat(){
 const [open,setOpen]=useState(false),[data,setData]=useState<any>(null),[target,setTarget]=useState(''),[text,setText]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[tick,setTick]=useState(0),[older,setOlder]=useState<any[]>([]),[olderCursor,setOlderCursor]=useState<string|null|undefined>(undefined),[loadingOlder,setLoadingOlder]=useState(false);
 const [seen,setSeen]=useState<Record<string,string>>({});
 const token=useRef(''),generation=useRef(0),end=useRef<HTMLDivElement>(null);
 useEffect(()=>{let alive=true;const current=++generation.current;async function refresh(){try{const r=await fetch('/api/chat?recipient='+encodeURIComponent(target),{cache:'no-store'});if(!alive||current!==generation.current)return;if(r.status===401||r.status===403){setData(null);return;}const d=await r.json();if(!r.ok)throw Error(d.error||'Could not load messages.');if(alive&&current===generation.current){setData(d);setError('');}}catch(e){if(alive)setError((e as Error).message);}}refresh();const timer=setInterval(refresh,open?5000:60000);return()=>{alive=false;clearInterval(timer)}},[target,open,tick]);
 useEffect(()=>{if(open&&!older.length)end.current?.scrollIntoView({block:'nearest'});},[open,data?.messages?.at(-1)?.id,older.length]);
 useEffect(()=>{if(!data?.actor?.id)return;try{setSeen(JSON.parse(localStorage.getItem('nv-chat-seen:'+data.actor.id)||'{}'));}catch{setSeen({})}},[data?.actor?.id]);
 useEffect(()=>{if(!open||!data)return;const admin=data.actor.role==='admin';const latest=data.messages.filter((m:any)=>m.fromAdmin!==admin).at(-1)?.createdAt;if(!latest)return;const key=admin?target:'reception';setSeen(old=>{if((old[key]||'')>=latest)return old;const next={...old,[key]:latest};try{localStorage.setItem('nv-chat-seen:'+data.actor.id,JSON.stringify(next));}catch{}return next;});},[open,target,data?.messages?.at(-1)?.id]);
 if(!data)return null;
 const admin=data.actor.role==='admin',broadcast=admin&&!target,contact=data.contacts.find((c:any)=>c.id===target),next=olderCursor===undefined?data.next:olderCursor;
 const unread=admin?data.contacts.filter((c:any)=>c.lastGuestMessage>(seen[c.id]||'')).length:data.messages.filter((m:any)=>m.fromAdmin&&m.createdAt>(seen.reception||'')).length;
 const messages=[...new Map([...older,...data.messages].map((m:any)=>[m.id,m])).values()] as any[];
 async function loadOlder(){if(!next||loadingOlder)return;const current=generation.current;setLoadingOlder(true);try{const r=await fetch('/api/chat?recipient='+encodeURIComponent(target)+'&before='+encodeURIComponent(next),{cache:'no-store'}),d=await r.json();if(!r.ok)throw Error(d.error);if(current!==generation.current)return;setOlder(v=>[...d.messages,...v]);setOlderCursor(d.next);}catch(e){setError((e as Error).message)}finally{setLoadingOlder(false)}}
 async function send(e:React.FormEvent){e.preventDefault();if(busy||!text.trim())return;if(broadcast&&!window.confirm('Send this announcement to '+data.inHouseCount+' checked-in guest accounts?'))return;setBusy(true);setError('');setNotice('');token.current||=crypto.randomUUID();try{const r=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text,recipient:target,broadcast,token:token.current})}),d=await r.json();if(!r.ok)throw Error(d.error||'Message was not sent.');setText('');token.current='';setNotice(broadcast?'Announcement saved for '+d.count+' guest accounts.':'Message sent.');setOlder([]);setOlderCursor(undefined);setTick(v=>v+1);}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <div className="nv-chat-root"><button className="nv-chat-launch" aria-expanded={open} onClick={()=>setOpen(v=>!v)}><MessageCircle size={21}/>{admin?'Guest messages':'Chat with reception'}{unread>0&&<span className="nv-chat-unread" aria-label={unread+' unread conversations'}>{unread}</span>}</button>{open&&<section className="nv-chat-panel" role="dialog" aria-label={admin?'Guest messages':'Chat with reception'}><header><div><strong>{admin?'Guest messages':'Nirili Villa reception'}</strong><small>Messages refresh automatically</small></div><button aria-label="Close messages" onClick={()=>setOpen(false)}><X size={21}/></button></header>{admin&&<div className="nv-chat-audience"><label>Send to<select disabled={busy} value={target} onChange={e=>{setTarget(e.target.value);setData((d:any)=>({...d,messages:[],next:null}));setOlder([]);setOlderCursor(undefined);setText('');token.current='';setError('');setNotice('');}}><option value="">All in-house guests ({data.inHouseCount})</option>{data.contacts.map((c:any)=><option key={c.id} value={c.id}>{c.lastGuestMessage>(seen[c.id]||'')?'● New · ':''}{c.name}{c.rooms.length?' · Room '+c.rooms.join(', '):''}{!c.active?' · Archived':''}</option>)}</select></label>{broadcast&&<p>Announcement to guests currently checked in with an active login.{data.withoutLogin>0?' '+data.withoutLogin+' occupied bookings need a guest login before they can receive messages.':''}</p>}{contact&&!contact.active&&<p>This account is archived. Conversation is read-only.</p>}</div>}<div className="nv-chat-messages" aria-label="Conversation">{next&&<button className="nv-chat-older" disabled={loadingOlder} onClick={loadOlder}>{loadingOlder?'Loading…':'Load earlier messages'}</button>}{!messages.length&&<p className="nv-chat-empty">{broadcast?'Send an announcement to everyone currently staying with us.':'Start a conversation. Messages stay saved here.'}</p>}{messages.map(m=><article key={m.id} className={m.fromAdmin===admin?'nv-chat-mine':''}><small>{m.sender}{m.broadcast?' · Announcement':''}</small><p>{m.text}</p><time dateTime={m.createdAt}>{new Date(m.createdAt).toLocaleString()}</time></article>)}<div ref={end}/></div><form onSubmit={send}><label className="nv-chat-input-label">{broadcast?'Announcement':'Message'}<textarea required maxLength={2000} rows={3} placeholder={broadcast?'Write an announcement…':'Write a message…'} disabled={busy||(admin&&!!contact&&!contact.active)} value={text} onChange={e=>{setText(e.target.value);token.current='';}}/></label>{error&&<p role="alert" className="nv-chat-error">{error}</p>}{notice&&<p role="status">{notice}</p>}<footer><small>{text.length}/2,000</small><button type="submit" disabled={busy||!text.trim()||(broadcast&&!data.inHouseCount)||(admin&&!!contact&&!contact.active)}><Send size={17}/>{busy?'Sending…':broadcast?'Send to all':'Send message'}</button></footer></form></section>}</div>;
}
