'use client';
import {UiText,UiField,UiOption} from './ui-language';

import {useState} from 'react';
const usd=(n:number)=>'$'+(n/100).toFixed(2);
const categories=['Accommodation','Restaurant','Transfer','Excursions'];
export default function GuestStayCard({stay:s,orders}:{stay:any;orders:any[]}){
 const [open,setOpen]=useState(false);
 return <article className="guest-stay-card"><span className="guest-stay-status"><UiText>{s.status}</UiText></span><h3>{s.guest} <UiText>· Room </UiText><UiText>{s.room}</UiText></h3><p><UiText>{s.id}</UiText> · <UiText>{s.checkIn}</UiText> → <UiText>{s.checkOut}</UiText></p><p><UiText>{s.meal}</UiText></p><div className="guest-bill-summary"><span><UiText>Total </UiText><b><UiText>{usd(s.folio.totalCents)}</UiText></b></span><span><UiText>Balance </UiText><b><UiText>{usd(s.folio.balanceCents)}</UiText></b></span></div><button className="primary guest-view-bills" aria-expanded={open} aria-controls={'guest-bills-'+s.id} onClick={()=>setOpen(!open)}><UiText>{open?'Hide bills':'View bills'}</UiText></button><UiText>{open&&<div id={'guest-bills-'+s.id} className="guest-bill-groups"><h4><UiText>Bills for Room </UiText><UiText>{s.room}</UiText></h4><UiText>{categories.map(category=>{const bills=s.folio.bills.filter((b:any)=>b.department===category);return <details key={category} className="guest-bill-category"><summary><span><UiText>{category}</UiText><small><UiText>{bills.length}</UiText> <UiText>{bills.length===1?'bill':'bills'}</UiText></small></span><strong><UiText>{usd(bills.reduce((n:number,b:any)=>n+b.totalCents,0))}</UiText></strong></summary><UiText>{!bills.length?<p><UiText>No </UiText><UiText>{category.toLowerCase()}</UiText> <UiText>bills for this stay.</UiText></p>:bills.map((bill:any)=><details key={bill.id} className="guest-bill"><summary><span><UiText>{bill.id}</UiText><small><UiText>{bill.status==='Paid'?'Paid':bill.status==='Cancelled'?'Cancelled':'Unpaid'}</UiText></small></span><strong><UiText>{usd(bill.totalCents)}</UiText></strong></summary><ul><UiText>{bill.items.map((row:any,i:number)=><li key={i}><span><UiText>{row[1]}</UiText> × <UiText>{row[0]}<UiText></UiText>{Number(row[3])>0&&<small><UiText>Discount </UiText><UiText>{row[3]}</UiText>%</small>}</UiText></span><b><UiText>{usd(Math.round(Math.round(Number(row[2])*100)*(1-(Number(row[3])||0)/100)))}</UiText></b></li>)}</UiText></ul></details>)}</UiText></details>})}</UiText><div className="guest-folio-totals"><p><span><UiText>Total bills</UiText></span><b><UiText>{usd(s.folio.totalCents)}</UiText></b></p><p><span><UiText>Payments received</UiText></span><b><UiText>{usd(s.folio.paidCents)}</UiText></b></p><p><span><UiText>Balance due</UiText></span><b><UiText>{usd(s.folio.balanceCents)}</UiText></b></p></div></div>}</UiText><details className="guest-stay-services"><summary><UiText>Services for this stay · </UiText><UiText>{orders.length}</UiText></summary><UiText>{!orders.length?<p><UiText>No service requests for this stay.</UiText></p>:orders.map(o=><div key={o.id}><b><UiText>{o.name}</UiText> × <UiText>{o.quantity}</UiText></b><p><UiText>{o.date}</UiText> <UiText>{o.time||''}</UiText> · <UiText>{o.status}</UiText></p><small><UiText>{o.id}</UiText> · <UiText>{usd(o.cents)}</UiText> · <UiText>{o.paymentStatus}</UiText></small></div>)}</UiText></details></article>
}
