"use client";
import {useEffect,useState} from "react";
import ExcursionCatalog from "./excursion-catalog";
import {catalog} from "../lib/guest-catalog";
export default function OperationsPanel({category,canEdit}:{category:string;canEdit:boolean}){
const [records,setRecords]=useState<any[]>([]),[edit,setEdit]=useState<any>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false);
useEffect(()=>{setRecords([]);fetch("/api/operations?category="+category).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error);setRecords(d.records)}).catch(e=>setError(e.message))},[category]);
async function save(){setBusy(true);setError("");try{const r=await fetch("/api/operations",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({category,record:edit})});const d=await r.json();if(!r.ok)throw new Error(d.error);setRecords(records.map(x=>x.id===d.record.id?d.record:x));setEdit(null);}catch(e){setError(e instanceof Error?e.message:"Unable to save");}finally{setBusy(false)}}
return <section className="page"><h1>{category==="Transfers"?"Transportation":category}</h1><>{category==="Excursions"&&<ExcursionCatalog items={catalog.filter(x=>x.kind==="excursion")}/>}</><p>{canEdit?"Select a record to edit.":"View only. Ask Admin for editing permission."}</p><p role="alert">{error}</p>{records.map(r=><div className="staff-row" key={r.id}><span><b>{r.time} · {r.service}</b><br/>{r.guests} guests · {r.boat} · {r.status}</span>{canEdit&&<button onClick={()=>setEdit({...r})}>Edit</button>}</div>)}{edit&&<form className="credentials-form" onSubmit={e=>{e.preventDefault();save()}}><h2>Edit {edit.id}</h2><fieldset disabled={busy} style={{border:0}}>{["time","service","guests","boat",category==="Transfers"?"guest":"guide","status"].map(k=><label key={k}>{k}<input required type={k==="time"?"time":k==="guests"?"number":"text"} min={1} value={edit[k]} onChange={e=>setEdit({...edit,[k]:k==="guests"?Number(e.target.value):e.target.value})}/></label>)}<button type="button" onClick={()=>setEdit(null)}>Cancel</button><button className="primary">Save changes</button></fieldset></form>}</section>;
}
