"use client";
import {startLiveRefresh} from '../lib/live-refresh';
import {UiText,UiField,UiOption} from './ui-language';
import {useEffect,useState} from "react";

export default function OperationsPanel({category,canEdit}:{category:string;canEdit:boolean}){
 const [records,setRecords]=useState<any[]>([]),[edit,setEdit]=useState<any>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 useEffect(()=>{if(category==="Excursions")return;setRecords([]);const reload=()=>fetch("/api/operations?category="+category).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error);setRecords(d.records)}).catch(e=>setError(e.message));reload();return startLiveRefresh(reload)},[category]);
 async function save(){setBusy(true);setError("");try{const r=await fetch("/api/operations",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({category,record:edit})});const d=await r.json();if(!r.ok)throw new Error(d.error);setRecords(records.map(x=>x.id===d.record.id?d.record:x));setEdit(null);}catch(e){setError(e instanceof Error?e.message:"Unable to save");}finally{setBusy(false)}}
 if(category==="Excursions")return null;
 return <section className="page"><h1><UiText>{category==="Transfers"?"Transportation":category}</UiText></h1><details className="legacy-excursion-records" open><summary>Operation records</summary><p><UiText>{canEdit?"Select a record to edit.":"View only. Ask Admin for editing permission."}</UiText></p><p role="alert"><UiText>{error}</UiText></p><UiText>{records.map(r=><div className="staff-row" key={r.id}><span><b><UiText>{r.time}</UiText> · <UiText>{r.service}</UiText></b><br/><UiText>{r.guests}</UiText> <UiText>guests · </UiText><UiText>{r.boat}</UiText> · <UiText>{r.status}</UiText></span><UiText>{canEdit&&<button onClick={()=>setEdit({...r})}><UiText>Edit</UiText></button>}</UiText></div>)}<UiText></UiText>{edit&&<form className="credentials-form" onSubmit={e=>{e.preventDefault();save()}}><h2><UiText>Edit </UiText><UiText>{edit.id}</UiText></h2><fieldset disabled={busy} style={{border:0}}><UiText>{["time","service","guests","boat",category==="Transfers"?"guest":"guide","status"].map(k=><label key={k}><UiText>{k}</UiText><input required type={k==="time"?"time":k==="guests"?"number":"text"} min={1} value={edit[k]} onChange={e=>setEdit({...edit,[k]:k==="guests"?Number(e.target.value):e.target.value})}/></label>)}</UiText><button type="button" onClick={()=>setEdit(null)}><UiText>Cancel</UiText></button><button className="primary"><UiText>Save changes</UiText></button></fieldset></form>}</UiText></details></section>;
}
