'use client';
import {UiText,UiField,UiOption} from './ui-language';

import {useState} from 'react';
export default function POSDiscountDialog({order,rooms,free,onSave,onClose}:{order:any;rooms:any[];free:boolean;onSave:(body:any)=>Promise<any>;onClose:()=>void}){
 const [percent,setPercent]=useState(String(order.billDiscountPercent||0)),[stayId,setStayId]=useState(order.stayId||''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const value=free?100:Number(percent),total=order.items.reduce((n:number,i:any)=>n+Math.round(i.unitCents*i.quantity*(1-value/100)),0);
 return <div className="menu-overlay"><UiField as="form" className="menu-dialog" role="dialog" aria-modal="true" aria-label={free?'Mark bill as free':'Bill percentage discount'} onSubmit={async e=>{e.preventDefault();if(busy)return;setBusy(true);setError('');try{await onSave({action:free?'free':'discount',id:order.id,percent:value,stayId});onClose();}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}><h2><UiText>{free?'Mark as free':'Discount bill'}</UiText></h2><p><UiText>{order.id}</UiText> · {order.customer}</p><UiText>{!free&&<label><UiText>Discount percentage</UiText><input required type="number" min="0" max="100" step="0.01" value={percent} disabled={busy} onChange={e=>setPercent(e.target.value)}/></label>}<UiText></UiText>{free&&<label><UiText>Guest room</UiText><select required disabled={!!order.stayId||busy} value={stayId} onChange={e=>setStayId(e.target.value)}><UiOption value="">Select a checked-in room</UiOption><UiText>{rooms.map(s=><UiOption key={s.id} value={s.id}>Room {s.room} · {s.guest}</UiOption>)}</UiText></select></label>}</UiText><p><UiText>{free?'The bill will be saved to this room as complimentary. No payment will be recorded.':'This percentage replaces existing item discounts across the entire bill. The linked room balance updates automatically.'}</UiText></p><h3><UiText>New total: $</UiText><UiText>{Number.isFinite(total)?(total/100).toFixed(2):'—'}</UiText></h3><UiText>{error&&<p role="alert"><UiText>{error}</UiText></p>}</UiText><footer><button type="button" disabled={busy} onClick={onClose}><UiText>Cancel</UiText></button><button className="primary" disabled={busy}><UiText>{busy?'Saving…':free?'Confirm free bill':'Apply discount'}</UiText></button></footer></UiField></div>;
}
