'use client';
import {useEffect,useState} from 'react';
import {restaurantTables} from '../lib/restaurant-tables';
export default function POSBillEditor({order,canDiscount,onSave,onClose}:{order:any;canDiscount:boolean;onSave:(body:any)=>Promise<any>;onClose:()=>void}){
 const [items,setItems]=useState<any[]>(order.items.map((i:any)=>({...i,price:(i.unitCents/100).toFixed(2),discount:i.discount||0}))),[table,setTable]=useState(order.table),[notes,setNotes]=useState(order.notes),[menu,setMenu]=useState<any[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{fetch('/api/menu').then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error);setMenu(d.items)}).catch(e=>setError(e.message))},[]);
 function update(n:number,key:string,value:any){setItems(rows=>rows.map((i,j)=>j===n?{...i,[key]:value}:i));}
 const total=items.reduce((n,i)=>n+Math.round(Math.round(Number(i.price)*100)*i.quantity*(1-i.discount/100)),0);
 return <div className="menu-overlay"><form className="menu-dialog pos-edit-dialog" role="dialog" aria-modal="true" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{await onSave({action:'edit',id:order.id,table,notes,items:items.map(i=>({id:i.id,name:i.name,quantity:Number(i.quantity),unitCents:Math.round(Number(i.price)*100),discount:Number(i.discount)}))});onClose();}catch(e){setError((e as Error).message);}finally{setBusy(false)}}}><h2>Edit Bill · {order.id}</h2><p>{order.customer} · {order.room?'Room '+order.room:'Walk-in'}</p><label>Table<select required value={table} onChange={e=>setTable(e.target.value)}><option value="">Select table</option>{restaurantTables.map(t=><option key={t}>{t}</option>)}</select></label><fieldset disabled={busy} style={{border:0,padding:0}}>{items.map((i,n)=><section className="pos-edit-line" key={i.id}><label>Item<input required maxLength={200} value={i.name} onChange={e=>update(n,'name',e.target.value)}/></label><div><label>Quantity<input required type="number" min="1" max="100" value={i.quantity} onChange={e=>update(n,'quantity',e.target.value)}/></label><label>Unit price USD<input required type="number" min="0" max="100000" step=".01" value={i.price} onChange={e=>update(n,'price',e.target.value)}/></label><label>Discount %<input required disabled={!canDiscount} type="number" min="0" max="100" step=".01" value={i.discount} onChange={e=>update(n,'discount',e.target.value)}/></label></div><button type="button" onClick={()=>setItems(rows=>rows.filter((_,j)=>j!==n))}>Remove item</button></section>)}<label>Add menu item<select value="" onChange={e=>{const product=menu.find(i=>i.id===e.target.value);if(!product)return;const n=items.findIndex(i=>i.id===product.id);if(n>=0)update(n,'quantity',Math.min(100,Number(items[n].quantity)+1));else setItems([...items,{id:product.id,name:product.category+' · '+product.name,quantity:1,price:(product.cents/100).toFixed(2),discount:0}]);}}><option value="">Choose an item…</option>{menu.map(i=><option key={i.id} value={i.id}>{i.category} · {i.name} · ${(i.cents/100).toFixed(2)}</option>)}</select></label><label>Kitchen notes<textarea maxLength={1000} value={notes} onChange={e=>setNotes(e.target.value)}/></label></fieldset><h3>Updated total ${(total/100).toFixed(2)}</h3><p>Changes update the room folio and kitchen ticket. Cashiers and Admin can change discounts.</p>{error&&<p role="alert">{error}</p>}<footer><button type="button" disabled={busy} onClick={onClose}>Cancel</button><button className="primary" disabled={busy||!items.length}>{busy?'Saving…':'Save changes'}</button></footer></form></div>;
}
