'use client';
import {useEffect,useState} from 'react';
import {Download,FileText,MessageCircle,Printer,Share2,X} from 'lucide-react';
import {createVoucherPdf} from '../lib/voucher-pdf';
import {downloadBill} from '../lib/bill-pdf';
import './stay-actions.css';
export default function VoucherButton({bookingId}:{bookingId:string}){
 const [file,setFile]=useState<File|null>(null),[guest,setGuest]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[canShare,setCanShare]=useState(false);
 useEffect(()=>{setFile(null);setError('');setNotice('')},[bookingId]);
 useEffect(()=>{if(!file)return;const esc=(e:KeyboardEvent)=>{if(e.key==='Escape')setFile(null)};window.addEventListener('keydown',esc);return()=>window.removeEventListener('keydown',esc)},[file]);
 async function prepare(){setBusy(true);setError('');setNotice('');try{const r=await fetch('/api/stays',{cache:'no-store'}),d=await r.json();if(!r.ok)throw Error(d.error);const stay=d.stays.find((s:any)=>s.id===bookingId);if(!stay)throw Error('Booking not found. Refresh the booking list.');const pdf=createVoucherPdf(stay,d.rooms.find((r:any)=>r.number===stay.room),d.requests?.find((q:any)=>q.stayId===stay.id));setGuest(stay);setFile(pdf);setCanShare(!!navigator.canShare?.({files:[pdf]}));}catch(e){setError((e as Error).message||'Could not create PDF. Please retry.')}finally{setBusy(false)}}
 async function share(){if(!file)return;setError('');if(!navigator.canShare?.({files:[file]})){setError('This browser cannot share PDF files. Save the PDF and attach it in WhatsApp, or open the application in a browser that supports file sharing.');return;}try{await navigator.share({files:[file],title:'Nirili Villa booking voucher '+bookingId});setNotice('Voucher handed to your sharing app. Confirm the recipient and send there.')}catch(e){if((e as any).name!=='AbortError')setError('Sharing failed. Please retry or save the PDF.')}}
 function openPdf(){if(!file)return;const url=URL.createObjectURL(file);window.open(url,'_blank','noopener,noreferrer');setTimeout(()=>URL.revokeObjectURL(url),60000);}
 return <><button onClick={prepare} disabled={busy}>{busy?'Preparing voucher…':'Print Voucher'}</button>{error&&!file&&<p role="alert">{error}</p>}{file&&<div className="stay-action-overlay" onClick={e=>{if(e.target===e.currentTarget)setFile(null)}}><section className="stay-action-dialog" role="dialog" aria-modal="true" aria-labelledby="voucher-title"><header><h2 id="voucher-title">Share booking voucher</h2><button autoFocus aria-label="Close voucher" onClick={()=>setFile(null)}><X/></button></header><p>{guest?.guest} · Room {guest?.room}<br/>{bookingId} · {guest?.status}</p><div className="invoice-file"><FileText/><div><b>{file.name}</b><small>Booking voucher · PDF</small></div></div>{guest?.whatsapp&&<p>Guest WhatsApp: <b>{guest.whatsapp}</b></p>}<div className="invoice-share-options"><button onClick={share}><MessageCircle/><span><b>WhatsApp</b><small>Share the PDF attachment</small></span></button>{canShare&&<button onClick={share}><Share2/><span><b>Share PDF to apps</b><small>WhatsApp, email and other installed apps</small></span></button>}<button onClick={()=>{downloadBill(file);setNotice('Voucher download requested.')}}><Download/><span><b>Save voucher PDF</b><small>Download to this device</small></span></button><button onClick={openPdf}><Printer/><span><b>Open / Print PDF</b><small>Open the voucher in your PDF viewer</small></span></button></div><p className="stay-help">Choose WhatsApp and the guest in your phone’s sharing menu. The voucher PDF is attached; the recipient must be selected manually.</p>{(error||notice)&&<p role="status">{error||notice}</p>}</section></div>}</>;
}
