'use client';
import {UiText,UiField,UiOption} from './ui-language';

import {useEffect,useState} from 'react';
import {Download,FileText,MessageCircle,Printer,Share2,X} from 'lucide-react';
import {createVoucherPdf} from '../lib/voucher-pdf';
import {downloadBill} from '../lib/bill-pdf';
import './stay-actions.css';
export default function VoucherButton({bookingId}:{bookingId:string}){
 const [file,setFile]=useState<File|null>(null),[guest,setGuest]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[canShare,setCanShare]=useState(false);
 useEffect(()=>{setFile(null);setError('');setNotice('')},[bookingId]);
 useEffect(()=>{if(!file)return;const esc=(e:KeyboardEvent)=>{if(e.key==='Escape')setFile(null)};window.addEventListener('keydown',esc);return()=>window.removeEventListener('keydown',esc)},[file]);
 async function prepare(){setBusy(true);setError('');setNotice('');try{const r=await fetch('/api/stays',{cache:'no-store'}),d=await r.json();if(!r.ok)throw Error(d.error);const stay=d.stays.find((s:any)=>s.id===bookingId);if(!stay)throw Error('Booking not found. Refresh the booking list.');const pdf=createVoucherPdf(stay,d.rooms.find((r:any)=>r.number===stay.room),d.requests?.find((q:any)=>q.stayId===stay.id));setGuest(stay);setFile(pdf);setCanShare(!!navigator.canShare?.({files:[pdf]}));}catch(e){setError((e as Error).message||'Could not create PDF. Please retry.')}finally{setBusy(false)}}
 async function share(){if(!file)return;setError('');if(!navigator.canShare?.({files:[file]})){setError('This browser cannot share PDF files. Save the PDF and attach it in WhatsApp, or open the application in a browser that supports file sharing.');return;}try{await navigator.share({files:[file],title:'Nirili Villa booking voucher '+bookingId});setNotice('Voucher handed to your sharing app. Confirm the recipient and send there.')}catch(e){if((e as any).name!=='AbortError')setError('Sharing failed. Please retry or save the PDF.')}}
 function openPdf(){if(!file)return;const url=URL.createObjectURL(file);window.open(url,'_blank','noopener,noreferrer');setTimeout(()=>URL.revokeObjectURL(url),60000);}
 return <><button onClick={prepare} disabled={busy}><UiText>{busy?'Preparing voucher…':'Print Voucher'}</UiText></button>{error&&!file&&<p role="alert"><UiText>{error}</UiText></p>}{file&&<div className="stay-action-overlay" onClick={e=>{if(e.target===e.currentTarget)setFile(null)}}><section className="stay-action-dialog" role="dialog" aria-modal="true" aria-labelledby="voucher-title"><header><h2 id="voucher-title"><UiText>Share booking voucher</UiText></h2><UiField as="button" autoFocus aria-label="Close voucher" onClick={()=>setFile(null)}><X/></UiField></header><p>{guest?.guest} <UiText>· Room </UiText><UiText>{guest?.room}</UiText><br/><UiText>{bookingId}</UiText> · <UiText>{guest?.status}</UiText></p><div className="invoice-file"><FileText/><div><b><UiText>{file.name}</UiText></b><small><UiText>Booking voucher · PDF</UiText></small></div></div><UiText>{guest?.whatsapp&&<p><UiText>Guest WhatsApp: </UiText><b>{guest.whatsapp}</b></p>}</UiText><div className="invoice-share-options"><button onClick={share}><MessageCircle/><span><b><UiText>WhatsApp</UiText></b><small><UiText>Share the PDF attachment</UiText></small></span></button><UiText>{canShare&&<button onClick={share}><Share2/><span><b><UiText>Share PDF to apps</UiText></b><small><UiText>WhatsApp, email and other installed apps</UiText></small></span></button>}</UiText><button onClick={()=>{downloadBill(file);setNotice('Voucher download requested.')}}><Download/><span><b><UiText>Save voucher PDF</UiText></b><small><UiText>Download to this device</UiText></small></span></button><button onClick={openPdf}><Printer/><span><b><UiText>Open / Print PDF</UiText></b><small><UiText>Open the voucher in your PDF viewer</UiText></small></span></button></div><p className="stay-help"><UiText>Choose WhatsApp and the guest in your phone’s sharing menu. The voucher PDF is attached; the recipient must be selected manually.</UiText></p><UiText>{(error||notice)&&<p role="status"><UiText>{error||notice}</UiText></p>}</UiText></section></div>}</>;
}
