"use client";
import {UiText,UiField,UiOption} from '../../../../ui-language';

import {useState} from "react";
import {Bill,total} from "../../../../../lib/restaurant";
export default function Editor({initial,isAdmin,currentRoom}:{initial:Bill;isAdmin:boolean;currentRoom:string}){
 const [bill,setBill]=useState(initial),[saved,setSaved]=useState(initial),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 function edit(i:number,j:number,value:string){setBill(b=>({...b,items:b.items.map((x,k)=>k===i?x.map((v,n)=>n===j?(j===0?value:Number(value)):v) as Bill["items"][number]:x)}));setMessage("");}
 async function save(){setBusy(true);setMessage("");try{const r=await fetch("/api/restaurant-bills",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(bill)});const d=await r.json();if(!r.ok)throw new Error(d.error);setBill(d.bill);setSaved(d.bill);setMessage("Bill saved. Room restaurant total updated.");}catch(e){setMessage(e instanceof Error?e.message:"Save failed. Please retry.");}finally{setBusy(false);}}
 return <main style={{maxWidth:850,margin:"24px auto",padding:20}}><a href={"/?room="+currentRoom}><UiText>← Back to Room </UiText><UiText>{currentRoom}</UiText></a><h1><UiText>Restaurant · Bill </UiText><UiText>{bill.id}</UiText></h1><p>{bill.guest} <UiText>· Room </UiText><UiText>{currentRoom}</UiText> · <UiText>{isAdmin?"Administrator":"Staff"}</UiText></p><p><UiText>Existing bills are demonstration records until edited. Amount is the full line amount, before discount.</UiText></p><form onSubmit={e=>{e.preventDefault();save();}}>
 <fieldset disabled={busy} style={{border:0,padding:0}}><label><UiText>Date and time </UiText><input required value={bill.date} onChange={e=>setBill({...bill,date:e.target.value})}/></label><label> <UiText>Status </UiText><select value={bill.status} onChange={e=>setBill({...bill,status:e.target.value})}><UiText>{["Posted","Pending","Paid","Unpaid","Cancelled"].map(s=><UiOption key={s}>{s}</UiOption>)}</UiText></select></label>
 <UiText>{bill.items.map((x,i)=><div key={i} style={{display:"flex",flexWrap:"wrap",gap:12,padding:16,marginTop:12,background:"white",border:"1px solid #cddfe9",borderRadius:8}}><UiText>{["Item","Quantity","Line amount (USD)","Discount %"].map((label,j)=><label key={label} style={{display:"grid",gap:6,flex:j===0?"1 1 230px":"1 1 100px",fontSize:14}}><UiText>{label}</UiText><input disabled={j===3&&!isAdmin} required style={{width:"100%",minWidth:0,padding:10}} type={j===0?"text":"number"} min={j===1?1:0} max={j===3?100:undefined} step={j===1?1:"any"} value={x[j]} onChange={e=>edit(i,j,e.target.value)}/></label>)}</UiText><button type="button" onClick={()=>setBill({...bill,items:bill.items.filter((_,k)=>k!==i)})}><UiText>Delete item</UiText></button></div>)}</UiText>
 <UiText>{!bill.items.length&&<p><UiText>No items. Add an item or save an empty bill.</UiText></p>}</UiText><button type="button" onClick={()=>setBill({...bill,items:[...bill.items,["",1,0,0]]})}><UiText>+ Add item</UiText></button><p><UiText>Subtotal: $</UiText><UiText>{bill.items.reduce((s,x)=>s+x[2],0).toFixed(2)}</UiText></p><p><UiText>Discount: $</UiText><UiText>{(bill.items.reduce((s,x)=>s+x[2],0)-total(bill)).toFixed(2)}</UiText></p><h2><UiText>Total: $</UiText><UiText>{total(bill).toFixed(2)}</UiText></h2><button type="button" onClick={()=>{setBill(saved);setMessage("Changes cancelled.");}}><UiText>Cancel changes</UiText></button> <button className="primary" type="submit"><UiText>{busy?"Saving…":"Save changes"}</UiText></button></fieldset><p role="status"><UiText>{message}</UiText></p></form></main>;
}
