"use client";
import {useState} from "react";
import {Bill,total} from "../../../../../lib/restaurant";
export default function Editor({initial,isAdmin,currentRoom}:{initial:Bill;isAdmin:boolean;currentRoom:string}){
 const [bill,setBill]=useState(initial),[saved,setSaved]=useState(initial),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 function edit(i:number,j:number,value:string){setBill(b=>({...b,items:b.items.map((x,k)=>k===i?x.map((v,n)=>n===j?(j===0?value:Number(value)):v) as Bill["items"][number]:x)}));setMessage("");}
 async function save(){setBusy(true);setMessage("");try{const r=await fetch("/api/restaurant-bills",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(bill)});const d=await r.json();if(!r.ok)throw new Error(d.error);setBill(d.bill);setSaved(d.bill);setMessage("Bill saved. Room restaurant total updated.");}catch(e){setMessage(e instanceof Error?e.message:"Save failed. Please retry.");}finally{setBusy(false);}}
 return <main style={{maxWidth:850,margin:"24px auto",padding:20}}><a href={"/?room="+currentRoom}>← Back to Room {currentRoom}</a><h1>Restaurant · Bill {bill.id}</h1><p>{bill.guest} · Room {currentRoom} · {isAdmin?"Administrator":"Staff"}</p><p>Existing bills are demonstration records until edited. Amount is the full line amount, before discount.</p><form onSubmit={e=>{e.preventDefault();save();}}>
 <fieldset disabled={busy} style={{border:0,padding:0}}><label>Date and time <input required value={bill.date} onChange={e=>setBill({...bill,date:e.target.value})}/></label><label> Status <select value={bill.status} onChange={e=>setBill({...bill,status:e.target.value})}>{["Posted","Pending","Paid","Unpaid","Cancelled"].map(s=><option key={s}>{s}</option>)}</select></label>
 {bill.items.map((x,i)=><div key={i} style={{display:"flex",flexWrap:"wrap",gap:12,padding:16,marginTop:12,background:"white",border:"1px solid #cddfe9",borderRadius:8}}>{["Item","Quantity","Line amount (USD)","Discount %"].map((label,j)=><label key={label} style={{display:"grid",gap:6,flex:j===0?"1 1 230px":"1 1 100px",fontSize:14}}>{label}<input disabled={j===3&&!isAdmin} required style={{width:"100%",minWidth:0,padding:10}} type={j===0?"text":"number"} min={j===1?1:0} max={j===3?100:undefined} step={j===1?1:"any"} value={x[j]} onChange={e=>edit(i,j,e.target.value)}/></label>)}<button type="button" onClick={()=>setBill({...bill,items:bill.items.filter((_,k)=>k!==i)})}>Delete item</button></div>)}
 {!bill.items.length&&<p>No items. Add an item or save an empty bill.</p>}<button type="button" onClick={()=>setBill({...bill,items:[...bill.items,["",1,0,0]]})}>+ Add item</button><p>Subtotal: ${bill.items.reduce((s,x)=>s+x[2],0).toFixed(2)}</p><p>Discount: ${(bill.items.reduce((s,x)=>s+x[2],0)-total(bill)).toFixed(2)}</p><h2>Total: ${total(bill).toFixed(2)}</h2><button type="button" onClick={()=>{setBill(saved);setMessage("Changes cancelled.");}}>Cancel changes</button> <button className="primary" type="submit">{busy?"Saving…":"Save changes"}</button></fieldset><p role="status">{message}</p></form></main>;
}
