import {stayInclusiveTaxBreakdown,SERVICE_CHARGE_RATE,TOURISM_GST_RATE,GREEN_TAX_USD_PER_PERSON_DAY} from './tax-inclusive';
// JPEG-backed A4 pages preserve the browser's Unicode font rendering in the PDF.
export function pdfFromPages(images:Uint8Array[],width=1240,height=1754):Uint8Array{
 const enc=new TextEncoder(),chunks:Uint8Array[]=[],offsets:number[]=[0];let length=0;
 const put=(v:string|Uint8Array)=>{const b=typeof v==='string'?enc.encode(v):v;chunks.push(b);length+=b.length};
 const obj=(id:number,value:string)=>{offsets[id]=length;put(`${id} 0 obj\n${value}\nendobj\n`)};
 put('%PDF-1.4\n');obj(1,'<< /Type /Catalog /Pages 2 0 R >>');obj(2,`<< /Type /Pages /Count ${images.length} /Kids [${images.map((_,i)=>`${3+i*3} 0 R`).join(' ')}] >>`);
 images.forEach((image,i)=>{const id=3+i*3;obj(id,`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595.28 841.89] /Resources << /XObject << /Im ${id+1} 0 R >> >> /Contents ${id+2} 0 R >>`);offsets[id+1]=length;put(`${id+1} 0 obj\n<< /Type /XObject /Subtype /Image /Width ${width} /Height ${height} /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ${image.length} >>\nstream\n`);put(image);put('\nendstream\nendobj\n');const commands='q\n595.28 0 0 841.89 0 0 cm\n/Im Do\nQ\n';obj(id+2,`<< /Length ${enc.encode(commands).length} >>\nstream\n${commands}endstream`)});
 const xref=length;put(`xref\n0 ${offsets.length}\n0000000000 65535 f \n`);for(let i=1;i<offsets.length;i++)put(String(offsets[i]).padStart(10,'0')+' 00000 n \n');put(`trailer\n<< /Size ${offsets.length} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`);const result=new Uint8Array(length);let pos=0;for(const c of chunks){result.set(c,pos);pos+=c.length}return result;
}
export function createBillPdf(stay:any):File{
 const w=1240,h=1754,margin=85,images:Uint8Array[]=[];const canvas=document.createElement('canvas');canvas.width=w;canvas.height=h;const ctx=canvas.getContext('2d');if(!ctx)throw Error('Could not prepare PDF. Please try another browser.');let y=0,page=0;
 const usd=(c:number)=>'$'+(c/100).toFixed(2);
 function finish(){ctx!.font='22px sans-serif';ctx!.fillStyle='#647987';ctx!.fillText('Nirili Villa · '+stay.id,margin,h-65);ctx!.textAlign='right';ctx!.fillText('Page '+page,w-margin,h-65);ctx!.textAlign='left';const raw=atob(canvas.toDataURL('image/jpeg',.94).split(',')[1]);images.push(Uint8Array.from(raw,c=>c.charCodeAt(0)));}
 function start(){page++;ctx!.fillStyle='white';ctx!.fillRect(0,0,w,h);ctx!.fillStyle='#083d57';ctx!.fillRect(0,0,w,14);ctx!.font='bold 39px sans-serif';ctx!.fillText('NIRILI VILLA',margin,96);ctx!.font='23px sans-serif';ctx!.fillStyle='#526c7c';ctx!.fillText('Dhiffushi Island, Maldives',margin,133);ctx!.textAlign='right';ctx!.fillText('INVOICE · '+stay.id,w-margin,96);ctx!.textAlign='left';y=190;}
 function line(text:string,bold=false,size=25){ctx!.font=`${bold?'bold ':''}${size}px sans-serif`;const rows:string[]=[];let row='';for(const ch of text){if(ch==='\n'||ctx!.measureText(row+ch).width>w-margin*2){rows.push(row);row=ch==='\n'?'':ch}else row+=ch}rows.push(row);for(const r of rows){if(y>h-140){finish();start();ctx!.font=`${bold?'bold ':''}${size}px sans-serif`;}ctx!.fillStyle=bold?'#083d57':'#233d4b';ctx!.fillText(r,margin,y);y+=size+13;}}
 start();line(stay.guest,true,31);line('Booking '+stay.id+' · Room '+stay.room+' · '+stay.status);line(stay.checkIn+' to '+stay.checkOut+' · '+stay.meal);if(stay.table)line(stay.table,true);if(stay.whatsapp)line('WhatsApp: '+stay.whatsapp);y+=15;
 for(const b of stay.folio.bills){line(b.department+' · '+b.id+' · '+b.status,true);for(const i of b.items){line(i[0]);line('Qty '+i[1]+'    Amount '+usd(Math.round(i[2]*100))+'    Discount '+(i[3]||0)+'%    Net '+usd(b.status==='Cancelled'?0:Math.round(i[2]*100*(1-(i[3]||0)/100))),false,22);}line('Bill total: '+usd(b.totalCents),true,24);y+=16;}
 const tax=stayInclusiveTaxBreakdown(stay.folio.totalCents,stay);line('Total charges: '+usd(stay.folio.totalCents),true,29);line('Included price before tax/service: '+usd(tax.baseCents),false,22);line('Included service charge '+Math.round(SERVICE_CHARGE_RATE*100)+'%: '+usd(tax.serviceChargeCents),false,22);line('Included Tourism GST '+Math.round(TOURISM_GST_RATE*100)+'%: '+usd(tax.tourismGstCents),false,22);line('Included Green Tax: '+usd(tax.greenTaxCents)+' (USD '+GREEN_TAX_USD_PER_PERSON_DAY+' per taxable guest/day)',false,22);line('All taxes and service charge are included in the total. Guest price is unchanged.',true,21);line('Payments received: '+usd(stay.folio.paidCents),true,27);line('Balance due: '+usd(stay.folio.balanceCents),true,31);y+=20;line('PAYMENTS',true);line('Opening payments: '+usd(stay.initialPaid));for(const p of stay.payments)line(p.date.slice(0,10)+' · '+p.method+' · '+usd(p.cents)+(p.reference?' · '+p.reference:''));y+=20;line('Arrive as a guest, leave as a friend.',false,23);finish();const bytes=pdfFromPages(images,w,h);return new File([bytes as BlobPart],`Nirili-Villa-Invoice-${stay.id}.pdf`,{type:'application/pdf'});
}
export function downloadBill(file:File){const url=URL.createObjectURL(file),link=document.createElement('a');link.href=url;link.download=file.name;document.body.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);}
export function whatsappBillUrl(stay:any){if(!/^\+[1-9]\d{7,14}$/.test(stay.whatsapp||''))throw Error('Save a WhatsApp number with country code first.');return 'https://wa.me/'+stay.whatsapp.slice(1)+'?text='+encodeURIComponent(`Hello ${stay.guest}, your Nirili Villa bill ${stay.id} for Room ${stay.room} is ready. Total: $${(stay.folio.totalCents/100).toFixed(2)}. Paid: $${(stay.folio.paidCents/100).toFixed(2)}. Balance: $${(stay.folio.balanceCents/100).toFixed(2)}.`)}
