import {roomNumbers,roomDetails,updateRoomInventory} from './rooms';
import {paidBillStatus} from './bill-payment';
import {authDb} from './auth';
import {readBill} from './restaurant-server';
import {total} from './restaurant';
export const stayKey='hotel-stays-v1';
export const money=(n:number)=>'$'+(n/100).toFixed(2);
export function seedStays(){return {rooms:roomNumbers.map((number,i)=>({number,...roomDetails,status:i===5?'Cleaning':i===9?'Maintenance':i<4?'Occupied':'Available',note:''})),stays:['Qiao Mingzhi','Liu Yutong','Marco Rossi','Victoria Chen'].map((guest,i)=>({id:'NV-'+(1260+i),guest,room:String(101+i),billRoom:String(101+i),checkIn:'2026-09-'+(12+i),checkOut:'2026-09-'+(15+i),meal:i===2?'Full Board':i===3?'Half Board':'Bed & Breakfast',source:'Direct',pax:2,status:'In House',base:[18000,24000,40000,32000][i],initialPaid:[18000,10000,40000,0][i],extensions:[] as any[],payments:[] as any[],history:[] as any[]}))};}
export async function loadStays(){const row=await authDb().prepare('SELECT payload,revision FROM operation_records WHERE key=?').bind(stayKey).first<any>();const state=row?JSON.parse(row.payload):seedStays();state.requests??=[];state.orders??=[];updateRoomInventory(state);return {state,revision:row?.revision||0};}
export async function folioFor(s:any,orders?:any[]){if(s.accountId&&!s.legacyFolio){const all=orders??(await loadStays()).state.orders;const bills=[...(s.posBills||[]),{department:'Accommodation',id:s.id,items:[[s.meal+' · '+s.checkIn+' to '+s.checkOut,1,s.base/100,0]],status:'Posted',totalCents:s.base},...all.filter((o:any)=>o.stayId===s.id&&o.status!=='Cancelled').map((o:any)=>({department:o.kind==='food'?'Restaurant':o.kind==='transfer'?'Transfer':'Excursions',id:o.id,items:[[o.name,o.quantity,o.cents/100,0]],status:o.status,totalCents:o.cents})),...s.extensions.map((e:any)=>({department:'Accommodation',id:e.id,items:[['Stay extension · '+e.from+' to '+e.to,e.nights,e.cents/100,0]],status:'Posted',totalCents:e.cents}))];const totalCents=bills.reduce((n:number,b:any)=>n+b.totalCents,0),paidCents=s.initialPaid+s.payments.reduce((n:number,p:any)=>n+p.cents,0);return {bills:bills.map((b:any)=>paidBillStatus(s,b)),totalCents,paidCents,balanceCents:totalCents-paidCents};}const rows=await authDb().prepare('SELECT payload FROM operation_records WHERE key LIKE ?').bind('folio:'+s.billRoom+':%').all<any>();const overrides=rows.results.map((x:any)=>JSON.parse(x.payload));
const bill=(department:string,id:string,items:any[])=>overrides.find((x:any)=>x.department===department&&x.id===id)||{department,id,items,status:'Posted'};
const bills=[bill('Accommodation',s.id,[[s.meal+' · '+s.checkIn+' to '+s.checkOut,1,s.base/100,0]]),...await Promise.all(['RES-1048','RES-1061'].map(async id=>({...await readBill(s.billRoom,id),department:'Restaurant'}))),bill('Transfer','TRF-0784',[['Airport → Dhiffushi shared speedboat',2,70,0]]),bill('Excursions','EXC-0921',[['Turtle Snorkeling',2,50,0]]),bill('Excursions','EXC-0934',[['Coral Garden + Sandbank',2,60,0]])].map((b:any)=>({...b,totalCents:b.status==='Cancelled'?0:Math.round(total({...b,items:b.items.map((i:any)=>[i[0],i[1],i[2],i[3]||0])})*100)}));
bills.push(...(s.posBills||[]));
const guestOrders=orders??(await loadStays()).state.orders;
bills.push(...guestOrders.filter((o:any)=>o.stayId===s.id&&o.status!=='Cancelled').map((o:any)=>({department:o.kind==='food'?'Restaurant':o.kind==='transfer'?'Transfer':'Excursions',id:o.id,items:[[o.name,o.quantity,o.cents/100,0]],status:o.status,totalCents:o.cents})));
for(const e of s.extensions)bills.push({department:'Accommodation',id:e.id,items:[['Stay extension · '+e.from+' to '+e.to,e.nights,e.cents/100,0]],status:'Posted',totalCents:e.cents});
const totalCents=bills.reduce((n:number,b:any)=>n+b.totalCents,0),paidCents=s.initialPaid+s.payments.reduce((n:number,p:any)=>n+p.cents,0);return {bills:bills.map((b:any)=>paidBillStatus(s,b)),totalCents,paidCents,balanceCents:totalCents-paidCents};}
export async function stayView(){const {state,revision}=await loadStays();return {...state,revision,stays:await Promise.all(state.stays.map(async(s:any)=>({...s,folio:await folioFor(s,state.orders)})))};}
