const receiptStyles=".receipt-page{min-height:100vh;background:#eaf0f4;padding:20px 12px;color:#000}.receipt-controls{max-width:520px;margin:0 auto 18px;display:flex;flex-wrap:wrap;justify-content:space-between;align-items:center;gap:12px;font:14px Arial,sans-serif}.receipt-controls button{padding:12px 16px;border:0;border-radius:9px;background:#087b79;color:white;min-height:44px}.receipt-controls p{flex-basis:100%;margin:0;font-size:12px;line-height:1.5;color:#405965}.restaurant-receipt{box-sizing:border-box;width:58mm;max-width:100%;margin:auto;background:white;padding:3mm;font:11px/1.4 Arial,Helvetica,sans-serif;color:#000;box-shadow:0 5px 20px #1232;overflow-wrap:anywhere}.restaurant-receipt *{box-sizing:border-box;color:#000}.restaurant-receipt header{text-align:center;border-bottom:1px dashed black;padding-bottom:3mm}.restaurant-receipt h1{font-size:18px;font-weight:800;letter-spacing:1px;margin:2mm 0}.restaurant-receipt header small{font-size:9px}.restaurant-receipt header p{font-size:10px;margin:1mm 0}.restaurant-receipt header b{font-size:11px}.receipt-meta{margin:3mm 0}.receipt-meta p,.receipt-totals p{display:flex;justify-content:space-between;gap:2mm;margin:1.5mm 0;font-size:11px}.receipt-meta p>span{flex-shrink:0}.receipt-meta b{text-align:right;font-weight:600;min-width:0}.restaurant-receipt table{width:100%;table-layout:fixed;border-collapse:collapse;font-size:11px}.restaurant-receipt th{border-top:1px dashed black;border-bottom:1px dashed black;padding:2mm 0;text-align:left;font-size:10px}.restaurant-receipt td{padding:2mm 0;border-bottom:1px dotted #555;vertical-align:top}.restaurant-receipt td:first-child{padding-right:2mm}.restaurant-receipt td:last-child,.restaurant-receipt th:last-child{width:16mm;text-align:right;white-space:nowrap}.restaurant-receipt td small{display:block;font-size:10px;margin-top:1mm}.receipt-totals{margin:3mm 0}.receipt-totals b{white-space:nowrap}.receipt-totals .receipt-grand{font-size:15px;font-weight:800;border-top:1px dashed black;padding-top:2mm}.receipt-status{display:block;text-align:center;border:1px solid black;padding:1.5mm;margin-top:3mm;text-transform:uppercase;font-size:11px}.restaurant-receipt footer{text-align:center;margin-top:4mm;font-size:10px}.restaurant-receipt footer p{margin:1mm 0}.restaurant-receipt footer small{font-size:9px}html,body{width:58mm!important;height:auto!important;min-height:0!important;margin:0!important;padding:0!important;background:white!important;overflow:visible!important}.restaurant-receipt{width:58mm!important;max-width:58mm!important;margin:0!important;box-shadow:none!important;height:auto!important;min-height:0!important;padding:2mm 3mm!important}.restaurant-receipt tr,.receipt-totals,.restaurant-receipt footer{break-inside:avoid}";
export function thermalHeight(heightPixels:number,widthPixels:number){if(!Number.isFinite(heightPixels)||!Number.isFinite(widthPixels)||heightPixels<=0||widthPixels<=0)throw Error('Receipt is not ready. Please try again.');return Math.ceil(heightPixels/widthPixels*58)+1;}
export async function printThermalReceipt(){
 const receipt=document.querySelector('.restaurant-receipt');if(!receipt)throw Error('Receipt not found.');
 document.getElementById('nv-thermal-frame')?.remove();
 const frame=document.createElement('iframe');frame.id='nv-thermal-frame';frame.title='58 mm receipt printing';frame.setAttribute('aria-hidden','true');frame.style.cssText='position:fixed;left:0;top:0;width:58mm;height:1px;border:0;opacity:0;pointer-events:none;';document.body.appendChild(frame);
 const doc=frame.contentDocument,win=frame.contentWindow;if(!doc||!win)throw Error('Print window unavailable.');
 doc.open();doc.write('<!doctype html><html><head><meta charset="utf-8"><title></title></head><body></body></html>');doc.close();
 const styles=doc.createElement('style');styles.textContent=receiptStyles;doc.head.appendChild(styles);const copy=receipt.cloneNode(true) as HTMLElement;doc.body.appendChild(copy);
 await doc.fonts.ready;await new Promise<void>(resolve=>win.requestAnimationFrame(()=>win.requestAnimationFrame(()=>resolve())));
 const rect=copy.getBoundingClientRect(),height=thermalHeight(rect.height,rect.width);const paper=doc.createElement('style');paper.textContent='@page { size:58mm '+height+'mm; margin:0; @top-left {content:none} @top-center {content:none} @top-right {content:none} @bottom-left {content:none} @bottom-center {content:none} @bottom-right {content:none} }';doc.head.appendChild(paper);
 // Measure only before printing: print pagination must not feed back into paper height.
 await new Promise<void>(resolve=>win.requestAnimationFrame(()=>resolve()));win.focus();win.print();return height;
}
