// Direct ESC/POS USB transport. Never loads QZ or invokes browser printing.
export const usbId=(d:any)=>JSON.stringify([d.vendorId,d.productId,d.serialNumber||'']);
function usb(){const api=(navigator as any).usb;if(!api)throw Error('Direct USB requires Chrome or Edge on the cashier computer.');return api;}
export function printerInterface(device:any){for(const config of device.configurations||[])for(const iface of config.interfaces)for(const alt of iface.alternates){if(alt.interfaceClass!==7&&alt.interfaceClass!==255)continue;const endpoint=alt.endpoints.find((e:any)=>e.direction==='out'&&e.type==='bulk');if(endpoint)return {config:config.configurationValue,iface:iface.interfaceNumber,alternate:alt.alternateSetting,endpoint:endpoint.endpointNumber};}throw Error('No supported USB printer interface found. This device requires a native Windows printing connection.');}
export async function usbStep<T>(task:Promise<T>,stage:string,ms=12000):Promise<T>{let timer:ReturnType<typeof setTimeout>;try{return await Promise.race([task,new Promise<T>((_,reject)=>{timer=setTimeout(()=>reject(Error(stage+' timed out. Disconnect and reconnect the USB cable, then retry.')),ms);})]);}finally{clearTimeout(timer!);}}
async function closeUSB(device:any){try{await usbStep(device.close(),'Closing USB',2000);}catch{}}
async function openPrinter(device:any,status:(text:string)=>void=()=>{}){let stage='Reading printer interface';const port=printerInterface(device);try{stage='Opening USB device';status(stage+'…');const opening=device.open();try{await usbStep(opening,stage);}catch(e){void opening.then(()=>closeUSB(device),()=>{});throw e;}if(device.configuration?.configurationValue!==port.config){stage='Selecting USB configuration';status(stage+'…');await usbStep(device.selectConfiguration(port.config),stage);}stage='Claiming printer interface';status(stage+'…');await usbStep(device.claimInterface(port.iface),stage);const active=device.configuration?.interfaces?.find((i:any)=>i.interfaceNumber===port.iface)?.alternate?.alternateSetting;if(active!==port.alternate){stage='Selecting printer endpoint';status(stage+'…');await usbStep(device.selectAlternateInterface(port.iface,port.alternate),stage);}return port;}catch(e){void closeUSB(device);throw Error(stage+' failed: '+((e as Error).message||String(e))+'. Windows driver access or another printer application may be involved. Keep your Aronium driver unchanged.');}}
export async function chooseUSBPrinter(status:(text:string)=>void=()=>{}){let device:any;status('Select your printer in the browser popup, then click Connect.');try{device=await usbStep(usb().requestDevice({filters:[{classCode:7},{classCode:255}]}),'Printer selection',120000);}catch(e){if((e as Error).name==='NotFoundError')throw Error('No printer selected. If DL-58 / 581PW is not listed, its Windows driver may not expose it to the browser.');throw e;}const name=device.productName||'USB receipt printer';status(name+' selected. Checking USB access…');const port=await openPrinter(device,text=>status(name+': '+text));status(name+': finishing connection check…');try{await usbStep(device.releaseInterface(port.iface),'Releasing test connection',3000);}finally{await closeUSB(device);}return {id:usbId(device),name};}
export function rasterCommands(width:number,height:number,rgba:Uint8ClampedArray){const rowBytes=Math.ceil(width/8),blocks:Uint8Array[]=[];for(let y=0;y<height;y+=128){const rows=Math.min(128,height-y),bytes=new Uint8Array(8+rowBytes*rows);bytes.set([29,118,48,0,rowBytes&255,rowBytes>>8,rows&255,rows>>8]);for(let j=0;j<rows;j++)for(let x=0;x<width;x++){const p=((y+j)*width+x)*4,alpha=rgba[p+3]/255;const luminance=(rgba[p]*.299+rgba[p+1]*.587+rgba[p+2]*.114)*alpha+255*(1-alpha);if(luminance<160)bytes[8+j*rowBytes+(x>>3)]|=128>>(x%8);}blocks.push(bytes);}return blocks;}
let printing=false;
export async function printUSB(id:string,canvas:HTMLCanvasElement,copies:number,feed:number){if(printing)throw Error('A USB print job is already running.');printing=true;let device:any,port:any,sent=false;try{const matches=(await usb().getDevices()).filter((d:any)=>usbId(d)===id);if(matches.length!==1)throw Error('Reconnect your USB printer in Printer settings. Connect only one identical printer when it has no serial number.');device=matches[0];const context=canvas.getContext('2d');if(!context)throw Error('Could not prepare the receipt.');const blocks=rasterCommands(canvas.width,canvas.height,context.getImageData(0,0,canvas.width,canvas.height).data);port=await openPrinter(device);async function write(bytes:Uint8Array){sent=true;const result=await device.transferOut(port.endpoint,bytes);if(result.status!=='ok'||result.bytesWritten!==bytes.length)throw Error('Incomplete USB transfer.');}for(let copy=0;copy<copies;copy++){await write(new Uint8Array([27,64]));for(const block of blocks)await write(block);if(feed)await write(new Uint8Array([27,100,feed]));}}catch(e){throw Error((e as Error).message+(sent?' The receipt may have printed partially. Check the paper before retrying.':''));}finally{if(device?.opened){try{if(port)await device.releaseInterface(port.iface);}catch{}try{await device.close();}catch{}}printing=false;}}
