import {pdfFromPages} from './bill-pdf';
type Row={text:string;heading?:boolean};
export function voucherRows(stay:any,room:any,request?:any):Row[]{
 const rows:Row[]=[],line=(text:string)=>rows.push({text}),heading=(text:string)=>rows.push({text,heading:true}),usd=(c:number)=>'$'+(c/100).toFixed(2);
 heading('BOOKING VOUCHER');line('Booking reference: '+stay.id);line('Reservation status: '+stay.status);
 heading('GUEST INFORMATION');line('Lead guest: '+stay.guest);line('Number of guests: '+stay.pax);if(stay.whatsapp)line('WhatsApp: '+stay.whatsapp);if(stay.email)line('Email: '+stay.email);if(stay.passport)line('Passport: '+stay.passport);
 if(Array.isArray(stay.guests))for(const g of stay.guests){if(g.name)line('Guest: '+g.name+(g.passport?' · Passport: '+g.passport:''));}
 heading('RESERVATION DETAILS');line('Property: Nirili Villa');line('Location: Dhiffushi Island, Kaafu Atoll, Maldives');line('Room: '+stay.room+' · '+(room?.type||'Room type not recorded'));line('Check-in: '+stay.checkIn+' · 14:00');line('Check-out: '+stay.checkOut+' · 12:00');const nights=Math.round((Date.parse(stay.checkOut)-Date.parse(stay.checkIn))/86400000);line('Length of stay: '+nights+(nights===1?' night':' nights'));line('Meal plan: '+stay.meal);line('Booking source: '+stay.source);
 heading('ACCOMMODATION & MEALS');line('Accommodation for the booked stay.');line(stay.meal==='Full Board'?'Meals: breakfast, lunch and dinner.':stay.meal==='Half Board'?'Meals: half-board plan. Confirm meal arrangements with reception.':stay.meal==='Bed & Breakfast'?'Meals: breakfast.':'Meal arrangements: '+stay.meal);
 heading('RECORDED SERVICES & CHARGES');for(const b of stay.folio.bills){line(b.department+' · '+b.id+' · '+b.status);for(const i of b.items)line('  '+i[0]+' · Qty '+i[1]+' · '+usd(Math.round(i[2]*100))+(i[3]?' · Discount '+i[3]+'%':''));line('  Total: '+usd(b.totalCents));}line('Only services recorded above are part of this voucher.');
 heading('PAYMENT SUMMARY');line('Total charges: '+usd(stay.folio.totalCents));line('Payments received: '+usd(stay.folio.paidCents));line('Balance due: '+usd(stay.folio.balanceCents));line('Payment status: '+(stay.folio.balanceCents>0?'Balance outstanding':stay.folio.balanceCents<0?'Credit balance':'Paid in full'));if(stay.initialPaid)line('Opening payments: '+usd(stay.initialPaid));for(const p of stay.payments||[])line(p.date.slice(0,10)+' · '+p.method+' · '+usd(p.cents)+(p.reference?' · '+p.reference:''));
 const notes=request?.notes||stay.guestNotes;if(notes){heading('GUEST REQUESTS');line(notes);}
 heading('ARRIVAL INFORMATION');line('Please present this voucher and valid passports upon arrival.');line('All times are local Maldives time (UTC+5).');line('Thank you for choosing Nirili Villa.');line('Arrive as a guest, leave as a friend.');return rows;
}
export function createVoucherPdf(stay:any,room:any,request?:any):File{
 const w=1240,h=1754,margin=85,images:Uint8Array[]=[];const canvas=document.createElement('canvas');canvas.width=w;canvas.height=h;const ctx=canvas.getContext('2d');if(!ctx)throw Error('Could not generate the voucher. Please retry.');let y=0,page=0;
 function start(){page++;ctx!.fillStyle='white';ctx!.fillRect(0,0,w,h);ctx!.fillStyle='#075574';ctx!.fillRect(0,0,w,16);ctx!.font='bold 38px sans-serif';ctx!.fillText('NIRILI VILLA',margin,95);ctx!.font='23px sans-serif';ctx!.fillStyle='#587585';ctx!.fillText('Dhiffushi Island, Maldives',margin,133);ctx!.textAlign='right';ctx!.fillText(stay.id,w-margin,95);ctx!.textAlign='left';y=185;}
 function finish(){ctx!.fillStyle='#587585';ctx!.font='20px sans-serif';ctx!.fillText('Booking voucher · '+stay.id,margin,h-65);ctx!.textAlign='right';ctx!.fillText('Page '+page,w-margin,h-65);ctx!.textAlign='left';images.push(Uint8Array.from(atob(canvas.toDataURL('image/jpeg',.94).split(',')[1]),c=>c.charCodeAt(0)));}
 start();for(const row of voucherRows(stay,room,request)){const size=row.heading?27:24;if(row.heading)y+=20;ctx.font=(row.heading?'bold ':'')+size+'px sans-serif';const lines:string[]=[];let text='';for(const c of row.text){if(c==='\n'||ctx.measureText(text+c).width>w-margin*2){lines.push(text);text=c==='\n'?'':c}else text+=c}lines.push(text);for(const value of lines){if(y>h-(row.heading?190:140)){finish();start();ctx.font=(row.heading?'bold ':'')+size+'px sans-serif';}ctx.fillStyle=row.heading?'#075574':'#253f4d';ctx.fillText(value,margin,y);y+=size+12;}}finish();return new File([pdfFromPages(images,w,h) as BlobPart],`Nirili-Villa-Voucher-${stay.id}.pdf`,{type:'application/pdf'});
}
