'use client';
import {useEffect,useState} from 'react';
import {tabNavigate} from '../../../lib/tab-navigation';
import './style.css';
export default function WalkInExcursions(){
 const [data,setData]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[itemId,setItem]=useState(''),[quantity,setQuantity]=useState(2),[date,setDate]=useState(''),[token,setToken]=useState(''),[success,setSuccess]=useState<any>(null);
 async function load(){try{const r=await fetch('/api/walkin-excursions'),d=await r.json();if(!r.ok)throw Error(d.error);setData(d);setError('');}catch(e){setError((e as Error).message);}}
 useEffect(()=>{load();setToken(crypto.randomUUID());},[]);
 const item=data?.items.find((i:any)=>i.id===itemId),money=(n:number)=>'$'+(n/100).toFixed(2);
 async function book(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;const f=new FormData(e.currentTarget);setBusy(true);setError('');try{const r=await fetch('/api/walkin-excursions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token,itemId,quantity,date,expectedCents:item.cents*quantity,name:f.get('name'),phone:String(f.get('phone')).replace(/[\s()-]/g,''),hotel:f.get('hotel'),room:f.get('room'),notes:f.get('notes')})}),d=await r.json();if(!r.ok)throw Error(d.error);setSuccess(d.order);setToken(crypto.randomUUID());await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <main className="walk-exc"><button className="walk-back" onClick={()=>tabNavigate('/login?portal=guest')}>← Back to guest options</button><header><small>NIRILI TOURS · DHIFFUSHI</small><h1>Book an excursion</h1><p>Visiting for the day or staying at another hotel? Join us on the water.</p><p>Reserve now, pay later. Our team will confirm your trip and departure time by WhatsApp. Minimum 2 guests.</p></header>{error&&<p role="alert">{error}</p>}{!data?<button onClick={load}>Load excursions</button>:success?<section role="status"><h2>Booking request received</h2><p>{success.name} · {success.quantity} guests · {success.date}</p><p>Total: {money(success.cents)} · Pay later</p><p>Reference: {success.id}</p><p>Your request is awaiting confirmation from our team.</p><button onClick={()=>setSuccess(null)}>Book another excursion</button></section>:<form onSubmit={book}><fieldset disabled={busy}><label>Excursion<select required value={itemId} onChange={e=>setItem(e.target.value)}><option value="">Choose an excursion</option>{data.items.map((i:any)=><option key={i.id} value={i.id}>{i.name} — {money(i.cents)} / person</option>)}</select></label>{item&&<p>{item.detail}</p>}<div className="walk-grid"><label>Number of guests<input required type="number" min={2} max={20} value={quantity} onChange={e=>setQuantity(Number(e.target.value))}/></label><label>Preferred date<input required type="date" min={data.today} value={date} onChange={e=>setDate(e.target.value)}/></label><label>Your name<input name="name" required maxLength={100} autoComplete="name"/></label><label>WhatsApp / contact number<input name="phone" type="tel" required maxLength={30} placeholder="+960…" autoComplete="tel"/></label><label>Hotel or meeting location<input name="hotel" required maxLength={150} placeholder="Hotel name, or visiting Dhiffushi"/></label><label>Hotel room (optional)<input name="room" maxLength={30}/></label></div><label>Notes (optional)<textarea name="notes" maxLength={1000} placeholder="Tell us about any requests"/></label>{item&&<p className="walk-total">Total USD {money(item.cents*quantity)} · Pay later</p>}<button type="submit" disabled={!item||!token}>{busy?'Sending…':'Book excursion'}</button></fieldset></form>}{data?.orders.length>0&&<section><h2>Your excursion requests</h2>{data.orders.slice().reverse().map((o:any)=><article key={o.id}><b>{o.name}</b><p>{o.date} · {o.quantity} guests · {money(o.cents)}</p><p>{o.status==='Placed'?'Awaiting confirmation':o.status}</p></article>)}</section>}</main>;
}
